
/**************
* This source file was generated by JUndo compiler version 050827A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See [put web site address here]
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.
* This File Generated : Fri Sep 02 21:44:17 MDT 2005
* From Input File : FlowBoxModel.JUndo
**************/

package verdantium.standard.flowbox;

class pdx_FlowBoxModel_pdx_PairRef extends jundo.runtime.ExtPair
	{
public pdx_FlowBoxModel_pdx_PairRef( pdx_FlowBoxModel_pdx_ObjectRef obj , jundo.runtime.ExtMilieuRef mil )
{
super( obj , mil );
}
	}

