
/**************
* This source file was generated by JUndo compiler version 050827A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See [put web site address here]
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.
* This File Generated : Fri Sep 02 21:44:16 MDT 2005
* From Input File : FlowBoxModel.JUndo
**************/

package verdantium.standard.flowbox;

class pdx_FlowBoxModel_pdx_ObjectRef extends jundo.runtime.ExtObjectRef
	{
protected pdx_FlowBoxModel_pdx_ObjectRef(  jundo.runtime.KeyRef Key )
{
super( Key );
}

public static verdantium.standard.flowbox.pdx_FlowBoxModel_pdx_PairRef createOID_FlowBoxModel( jundo.runtime.ExtMilieuRef InMil )
{
jundo.runtime.ExtMilieuRef NewMil = jundo.runtime.Runtime.createOIDmilieu( InMil );
int NewID = NewMil.getMaxID();
jundo.runtime.KeyRef MyKey = jundo.runtime.Runtime.getKeyRef( NewID );
pdx_FlowBoxModel_pdx_ObjectRef NewObj = 
	new pdx_FlowBoxModel_pdx_ObjectRef( MyKey );
verdantium.standard.flowbox.pdx_FlowBoxModel_pdx_PairRef ret = new verdantium.standard.flowbox.pdx_FlowBoxModel_pdx_PairRef( NewObj , NewMil );
return( ret );
}
	public static verdantium.standard.flowbox.pdx_FlowBoxModel_pdx_PairRef pdxm_new_FlowBoxModel( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final boolean  onlyDesignerEdits , final int  img_size , final int  tbl_size , final int  tbl_delay , final int  num_frames , final int  currentMode , final java.lang.Object  endColor , final java.lang.Object  midColor , final java.lang.Object  startColor )
{
final verdantium.standard.flowbox.pdx_FlowBoxModel_pdx_PairRef pdx_tmp_6282 = verdantium.standard.flowbox.pdx_FlowBoxModel_pdx_ObjectRef.pdxm_allocate_FlowBoxModel( ( pdx_thismilieu ) );
final verdantium.standard.flowbox.pdx_FlowBoxModel_pdx_ObjectRef pdx_tmp_6280 = (verdantium.standard.flowbox.pdx_FlowBoxModel_pdx_ObjectRef)( pdx_tmp_6282.getObject() );
final jundo.runtime.ExtMilieuRef pdx_tmp_6281 = pdx_tmp_6282.getMilieu();
final jundo.runtime.ExtMilieuRef pdx_tmp_6600 = pdx_tmp_6280.pdxm_setOnlyDesignerEdits( pdx_tmp_6281 , ( onlyDesignerEdits ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_6760 = pdx_tmp_6280.pdxm_setResolution( pdx_tmp_6600 , ( img_size ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_6920 = pdx_tmp_6280.pdxm_setColorTableSize( pdx_tmp_6760 , ( tbl_size ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_7080 = pdx_tmp_6280.pdxm_setDelay( pdx_tmp_6920 , ( tbl_delay ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_7240 = pdx_tmp_6280.pdxm_setNumFrames( pdx_tmp_7080 , ( num_frames ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_7400 = pdx_tmp_6280.pdxm_setEditMode( pdx_tmp_7240 , ( currentMode ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_7560 = pdx_tmp_6280.pdxm_setEndColor( pdx_tmp_7400 , ( endColor ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_7720 = pdx_tmp_6280.pdxm_setMidColor( pdx_tmp_7560 , ( midColor ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_7880 = pdx_tmp_6280.pdxm_setStartColor( pdx_tmp_7720 , ( startColor ) );
return( new verdantium.standard.flowbox.pdx_FlowBoxModel_pdx_PairRef( pdx_tmp_6280 , ( pdx_tmp_7880 ) ) );
}
	public static verdantium.standard.flowbox.pdx_FlowBoxModel_pdx_PairRef pdxm_allocate_FlowBoxModel( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.standard.flowbox.pdx_FlowBoxModel_pdx_PairRef t1 = pdx_FlowBoxModel_pdx_ObjectRef.createOID_FlowBoxModel( pdx_thismilieu );
final verdantium.standard.flowbox.pdx_FlowBoxModel_pdx_PairRef t2 = pdx_zero( t1.getMilieu() , (verdantium.standard.flowbox.pdx_FlowBoxModel_pdx_ObjectRef)( t1.getObject() ) );

return( t2 );
}
	public static verdantium.standard.flowbox.pdx_FlowBoxModel_pdx_PairRef pdx_zero( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final verdantium.standard.flowbox.pdx_FlowBoxModel_pdx_ObjectRef in )
{
final verdantium.standard.flowbox.pdx_FlowBoxModel_pdx_PairRef tx = new verdantium.standard.flowbox.pdx_FlowBoxModel_pdx_PairRef( in , pdx_thismilieu );
final jundo.runtime.ExtMilieuRef t0 = tx.getMilieu();
final jundo.runtime.ExtMilieuRef t1 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "midColor" , t0 , null );
final jundo.runtime.ExtMilieuRef t2 = jundo.runtime.Runtime.asgIntObjectMember( tx.getObject() , "num_frames" , t1 , 0 );
final jundo.runtime.ExtMilieuRef t3 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "startColor" , t2 , null );
final jundo.runtime.ExtMilieuRef t4 = jundo.runtime.Runtime.asgIntObjectMember( tx.getObject() , "tbl_delay" , t3 , 0 );
final jundo.runtime.ExtMilieuRef t5 = jundo.runtime.Runtime.asgBooleanObjectMember( tx.getObject() , "onlyDesignerEdits" , t4 , false );
final jundo.runtime.ExtMilieuRef t6 = jundo.runtime.Runtime.asgIntObjectMember( tx.getObject() , "img_size" , t5 , 0 );
final jundo.runtime.ExtMilieuRef t7 = jundo.runtime.Runtime.asgIntObjectMember( tx.getObject() , "tbl_size" , t6 , 0 );
final jundo.runtime.ExtMilieuRef t8 = jundo.runtime.Runtime.asgIntObjectMember( tx.getObject() , "currentMode" , t7 , 0 );
final jundo.runtime.ExtMilieuRef t9 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "endColor" , t8 , null );
final verdantium.standard.flowbox.pdx_FlowBoxModel_pdx_PairRef z = new verdantium.standard.flowbox.pdx_FlowBoxModel_pdx_PairRef( in , t9 );
return( z );
}
	public static void pdx_initClassMembers( )
{
}

	static
{
pdx_initClassMembers();
}

	public java.lang.Object pdx_ObjectMemberAccess_pdx_getmidColor( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "midColor" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgmidColor( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "midColor" , mil , val ) );
}
	public int pdx_ObjectMemberAccess_pdx_getnum_frames( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getIntObjectMember( this , "num_frames" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgnum_frames( final jundo.runtime.ExtMilieuRef mil , final int val )
{
return( jundo.runtime.Runtime.asgIntObjectMember( this , "num_frames" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getstartColor( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "startColor" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgstartColor( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "startColor" , mil , val ) );
}
	public int pdx_ObjectMemberAccess_pdx_gettbl_delay( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getIntObjectMember( this , "tbl_delay" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgtbl_delay( final jundo.runtime.ExtMilieuRef mil , final int val )
{
return( jundo.runtime.Runtime.asgIntObjectMember( this , "tbl_delay" , mil , val ) );
}
	public boolean pdx_ObjectMemberAccess_pdx_getonlyDesignerEdits( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getBooleanObjectMember( this , "onlyDesignerEdits" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgonlyDesignerEdits( final jundo.runtime.ExtMilieuRef mil , final boolean val )
{
return( jundo.runtime.Runtime.asgBooleanObjectMember( this , "onlyDesignerEdits" , mil , val ) );
}
	public int pdx_ObjectMemberAccess_pdx_getimg_size( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getIntObjectMember( this , "img_size" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgimg_size( final jundo.runtime.ExtMilieuRef mil , final int val )
{
return( jundo.runtime.Runtime.asgIntObjectMember( this , "img_size" , mil , val ) );
}
	public int pdx_ObjectMemberAccess_pdx_gettbl_size( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getIntObjectMember( this , "tbl_size" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgtbl_size( final jundo.runtime.ExtMilieuRef mil , final int val )
{
return( jundo.runtime.Runtime.asgIntObjectMember( this , "tbl_size" , mil , val ) );
}
	public int pdx_ObjectMemberAccess_pdx_getcurrentMode( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getIntObjectMember( this , "currentMode" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgcurrentMode( final jundo.runtime.ExtMilieuRef mil , final int val )
{
return( jundo.runtime.Runtime.asgIntObjectMember( this , "currentMode" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getendColor( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "endColor" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgendColor( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "endColor" , mil , val ) );
}
	public jundo.runtime.ExtMilieuRef pdxm_setColorTableSize( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final int  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_2240 = ( this ).pdx_ObjectMemberAccess_pdx_asgtbl_size( pdx_thismilieu , ( in ) );
return( pdx_tmp_2240 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setMidColor( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_4640 = ( this ).pdx_ObjectMemberAccess_pdx_asgmidColor( pdx_thismilieu , ( in ) );
return( pdx_tmp_4640 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setDelay( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final int  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_2720 = ( this ).pdx_ObjectMemberAccess_pdx_asgtbl_delay( pdx_thismilieu , ( in ) );
return( pdx_tmp_2720 );
}
	public int pdxm_getColorTableSize( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final int pdx_tmp_2000 = ( this ).pdx_ObjectMemberAccess_pdx_gettbl_size( pdx_thismilieu );
return( pdx_tmp_2000 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setStartColor( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_5120 = ( this ).pdx_ObjectMemberAccess_pdx_asgstartColor( pdx_thismilieu , ( in ) );
return( pdx_tmp_5120 );
}
	public java.lang.Object pdxm_getEndColor( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_3920 = ( this ).pdx_ObjectMemberAccess_pdx_getendColor( pdx_thismilieu );
return( pdx_tmp_3920 );
}
	public java.lang.Object pdxm_getMidColor( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_4400 = ( this ).pdx_ObjectMemberAccess_pdx_getmidColor( pdx_thismilieu );
return( pdx_tmp_4400 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setResolution( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final int  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_1760 = ( this ).pdx_ObjectMemberAccess_pdx_asgimg_size( pdx_thismilieu , ( in ) );
return( pdx_tmp_1760 );
}
	public int pdxm_getEditMode( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final int pdx_tmp_3440 = ( this ).pdx_ObjectMemberAccess_pdx_getcurrentMode( pdx_thismilieu );
return( pdx_tmp_3440 );
}
	public int pdxm_getDelay( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final int pdx_tmp_2480 = ( this ).pdx_ObjectMemberAccess_pdx_gettbl_delay( pdx_thismilieu );
return( pdx_tmp_2480 );
}
	public java.lang.Object pdxm_getStartColor( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_4880 = ( this ).pdx_ObjectMemberAccess_pdx_getstartColor( pdx_thismilieu );
return( pdx_tmp_4880 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setEditMode( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final int  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_3680 = ( this ).pdx_ObjectMemberAccess_pdx_asgcurrentMode( pdx_thismilieu , ( in ) );
return( pdx_tmp_3680 );
}
	public boolean pdxm_isOnlyDesignerEdits( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final boolean pdx_tmp_1040 = ( this ).pdx_ObjectMemberAccess_pdx_getonlyDesignerEdits( pdx_thismilieu );
return( pdx_tmp_1040 );
}
	public int pdxm_getResolution( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final int pdx_tmp_1520 = ( this ).pdx_ObjectMemberAccess_pdx_getimg_size( pdx_thismilieu );
return( pdx_tmp_1520 );
}
	public int pdxm_getNumFrames( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final int pdx_tmp_2960 = ( this ).pdx_ObjectMemberAccess_pdx_getnum_frames( pdx_thismilieu );
return( pdx_tmp_2960 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setOnlyDesignerEdits( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final boolean  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_1280 = ( this ).pdx_ObjectMemberAccess_pdx_asgonlyDesignerEdits( pdx_thismilieu , ( in ) );
return( pdx_tmp_1280 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setEndColor( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_4160 = ( this ).pdx_ObjectMemberAccess_pdx_asgendColor( pdx_thismilieu , ( in ) );
return( pdx_tmp_4160 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setNumFrames( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final int  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_3200 = ( this ).pdx_ObjectMemberAccess_pdx_asgnum_frames( pdx_thismilieu , ( in ) );
return( pdx_tmp_3200 );
}
	}

