
/**************
* This source file was generated by JUndo compiler version 051002A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See http://sourceforge.net/projects/jundo
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.  See the associated .JUndo file for license and
* copyright information.
* This File Generated : Fri Oct 28 21:32:57 MDT 2005
* From Input File : UndoNode.JUndo
**************/

package verdantium.undo;

class pdx_UndoNode_pdx_ObjectRef extends jundo.runtime.ExtObjectRef
	{
protected pdx_UndoNode_pdx_ObjectRef( jundo.runtime.KeyRef Key )
{
super( Key );
}

public static verdantium.undo.pdx_UndoNode_pdx_PairRef createOID_UndoNode( jundo.runtime.ExtMilieuRef InMil )
{
jundo.runtime.ExtMilieuRef NewMil = jundo.runtime.Runtime.createOIDmilieu( InMil );
int NewID = NewMil.getMaxID();
jundo.runtime.KeyRef MyKey = jundo.runtime.Runtime.getKeyRef( NewID );
pdx_UndoNode_pdx_ObjectRef NewObj = 
	new pdx_UndoNode_pdx_ObjectRef( MyKey );
verdantium.undo.pdx_UndoNode_pdx_PairRef ret = new verdantium.undo.pdx_UndoNode_pdx_PairRef( NewObj , NewMil );
return( ret );
}
	public static verdantium.undo.pdx_UndoNode_pdx_PairRef pdxm_allocate_UndoNode( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.undo.pdx_UndoNode_pdx_PairRef t1 = pdx_UndoNode_pdx_ObjectRef.createOID_UndoNode( pdx_thismilieu );
final verdantium.undo.pdx_UndoNode_pdx_PairRef t2 = pdx_zero( t1.getMilieu() , (verdantium.undo.pdx_UndoNode_pdx_ObjectRef)( t1.getObject() ) );

return( t2 );
}
	public static verdantium.undo.pdx_UndoNode_pdx_PairRef pdx_zero( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final verdantium.undo.pdx_UndoNode_pdx_ObjectRef in )
{
final verdantium.undo.pdx_UndoNode_pdx_PairRef tx = new verdantium.undo.pdx_UndoNode_pdx_PairRef( in , pdx_thismilieu );
final jundo.runtime.ExtMilieuRef t0 = tx.getMilieu();
final jundo.runtime.ExtMilieuRef t1 = jundo.runtime.Runtime.asgObjectObjectMember( tx.getObject() , "state" , t0 , null );
final jundo.runtime.ExtMilieuRef t2 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "undoDesc" , t1 , null );
final jundo.runtime.ExtMilieuRef t3 = jundo.runtime.Runtime.asgBooleanObjectMember( tx.getObject() , "fileSavePoint" , t2 , false );
final jundo.runtime.ExtMilieuRef t4 = jundo.runtime.Runtime.asgObjectObjectMember( tx.getObject() , "nxt" , t3 , null );
final verdantium.undo.pdx_UndoNode_pdx_PairRef z = new verdantium.undo.pdx_UndoNode_pdx_PairRef( in , t4 );
return( z );
}
	public static void pdx_initClassMembers( )
{
}

	static
{
pdx_initClassMembers();
}

	public jundo.util.pdx_MilieuRef_pdx_ObjectRef pdx_ObjectMemberAccess_pdx_getstate( final jundo.runtime.ExtMilieuRef mil )
{
return( (jundo.util.pdx_MilieuRef_pdx_ObjectRef)( jundo.runtime.Runtime.getObjectObjectMember( this , "state" , mil ) ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgstate( final jundo.runtime.ExtMilieuRef mil , final jundo.util.pdx_MilieuRef_pdx_ObjectRef val )
{
return( jundo.runtime.Runtime.asgObjectObjectMember( this , "state" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getundoDesc( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "undoDesc" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgundoDesc( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "undoDesc" , mil , val ) );
}
	public boolean pdx_ObjectMemberAccess_pdx_getfileSavePoint( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getBooleanObjectMember( this , "fileSavePoint" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgfileSavePoint( final jundo.runtime.ExtMilieuRef mil , final boolean val )
{
return( jundo.runtime.Runtime.asgBooleanObjectMember( this , "fileSavePoint" , mil , val ) );
}
	public verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_ObjectMemberAccess_pdx_getnxt( final jundo.runtime.ExtMilieuRef mil )
{
return( (verdantium.undo.pdx_UndoNode_pdx_ObjectRef)( jundo.runtime.Runtime.getObjectObjectMember( this , "nxt" , mil ) ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgnxt( final jundo.runtime.ExtMilieuRef mil , final verdantium.undo.pdx_UndoNode_pdx_ObjectRef val )
{
return( jundo.runtime.Runtime.asgObjectObjectMember( this , "nxt" , mil , val ) );
}
	public jundo.runtime.ExtMilieuRef pdxm_setNxt( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final verdantium.undo.pdx_UndoNode_pdx_ObjectRef  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_980 = ( this ).pdx_ObjectMemberAccess_pdx_asgnxt( pdx_thismilieu , ( in ) );
return( pdx_tmp_980 );
}
	public jundo.util.pdx_MilieuRef_pdx_ObjectRef pdxm_getState( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final jundo.util.pdx_MilieuRef_pdx_ObjectRef pdx_tmp_1220 = ( this ).pdx_ObjectMemberAccess_pdx_getstate( pdx_thismilieu );
return( pdx_tmp_1220 );
}
	public verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdxm_getNxt( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_740 = ( this ).pdx_ObjectMemberAccess_pdx_getnxt( pdx_thismilieu );
return( pdx_tmp_740 );
}
	public java.lang.Object pdxm_getUndoDesc( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_2180 = ( this ).pdx_ObjectMemberAccess_pdx_getundoDesc( pdx_thismilieu );
return( pdx_tmp_2180 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setState( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final jundo.util.pdx_MilieuRef_pdx_ObjectRef  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_1460 = ( this ).pdx_ObjectMemberAccess_pdx_asgstate( pdx_thismilieu , ( in ) );
return( pdx_tmp_1460 );
}
	public boolean pdxm_isFileSavePoint( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final boolean pdx_tmp_1700 = ( this ).pdx_ObjectMemberAccess_pdx_getfileSavePoint( pdx_thismilieu );
return( pdx_tmp_1700 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setUndoDesc( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_2420 = ( this ).pdx_ObjectMemberAccess_pdx_asgundoDesc( pdx_thismilieu , ( in ) );
return( pdx_tmp_2420 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setFileSavePoint( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final boolean  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_1940 = ( this ).pdx_ObjectMemberAccess_pdx_asgfileSavePoint( pdx_thismilieu , ( in ) );
return( pdx_tmp_1940 );
}
	}

