
/**************
* This source file was generated by JUndo compiler version 051002A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See http://sourceforge.net/projects/jundo
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.  See the associated .JUndo file for license and
* copyright information.
* This File Generated : Tue Oct 18 19:06:46 MDT 2005
* From Input File : UndoImpl.JUndo
**************/

package verdantium.undo;

class pdx_UndoImpl_pdx_ObjectRef extends jundo.runtime.ExtObjectRef
	{
protected pdx_UndoImpl_pdx_ObjectRef( jundo.runtime.KeyRef Key )
{
super( Key );
}

public static verdantium.undo.pdx_UndoImpl_pdx_PairRef createOID_UndoImpl( jundo.runtime.ExtMilieuRef InMil )
{
jundo.runtime.ExtMilieuRef NewMil = jundo.runtime.Runtime.createOIDmilieu( InMil );
int NewID = NewMil.getMaxID();
jundo.runtime.KeyRef MyKey = jundo.runtime.Runtime.getKeyRef( NewID );
pdx_UndoImpl_pdx_ObjectRef NewObj = 
	new pdx_UndoImpl_pdx_ObjectRef( MyKey );
verdantium.undo.pdx_UndoImpl_pdx_PairRef ret = new verdantium.undo.pdx_UndoImpl_pdx_PairRef( NewObj , NewMil );
return( ret );
}
	public static verdantium.undo.pdx_UndoImpl_pdx_PairRef pdxm_new_UndoImpl( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final jundo.util.pdx_MilieuRef_pdx_ObjectRef  initialMil )
{
final verdantium.undo.pdx_UndoImpl_pdx_PairRef pdx_tmp_12362 = verdantium.undo.pdx_UndoImpl_pdx_ObjectRef.pdxm_allocate_UndoImpl( ( pdx_thismilieu ) );
final verdantium.undo.pdx_UndoImpl_pdx_ObjectRef pdx_tmp_12360 = (verdantium.undo.pdx_UndoImpl_pdx_ObjectRef)( pdx_tmp_12362.getObject() );
final jundo.runtime.ExtMilieuRef pdx_tmp_12361 = pdx_tmp_12362.getMilieu();
final verdantium.undo.pdx_UndoNode_pdx_PairRef pdx_tmp_12622 = verdantium.undo.pdx_UndoNode_pdx_ObjectRef.pdxm_allocate_UndoNode( pdx_tmp_12361 );
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_12620 = (verdantium.undo.pdx_UndoNode_pdx_ObjectRef)( pdx_tmp_12622.getObject() );
final jundo.runtime.ExtMilieuRef pdx_tmp_12621 = pdx_tmp_12622.getMilieu();
final jundo.runtime.ExtMilieuRef pdx_tmp_12800 = pdx_tmp_12360.pdx_ObjectMemberAccess_pdx_asgcurrentState( pdx_tmp_12621 , pdx_tmp_12620 );
final jundo.runtime.ExtMilieuRef pdx_tmp_13120 = pdx_tmp_12620.pdxm_setState( pdx_tmp_12800 , ( initialMil ) );
return( new verdantium.undo.pdx_UndoImpl_pdx_PairRef( pdx_tmp_12360 , ( pdx_tmp_13120 ) ) );
}
	public static verdantium.undo.pdx_UndoImpl_pdx_PairRef pdxm_allocate_UndoImpl( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.undo.pdx_UndoImpl_pdx_PairRef t1 = pdx_UndoImpl_pdx_ObjectRef.createOID_UndoImpl( pdx_thismilieu );
final verdantium.undo.pdx_UndoImpl_pdx_PairRef t2 = pdx_zero( t1.getMilieu() , (verdantium.undo.pdx_UndoImpl_pdx_ObjectRef)( t1.getObject() ) );

return( t2 );
}
	public static verdantium.undo.pdx_UndoImpl_pdx_PairRef pdx_zero( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final verdantium.undo.pdx_UndoImpl_pdx_ObjectRef in )
{
final verdantium.undo.pdx_UndoImpl_pdx_PairRef tx = new verdantium.undo.pdx_UndoImpl_pdx_PairRef( in , pdx_thismilieu );
final jundo.runtime.ExtMilieuRef t0 = tx.getMilieu();
final jundo.runtime.ExtMilieuRef t1 = jundo.runtime.Runtime.asgObjectObjectMember( tx.getObject() , "redoStk" , t0 , null );
final jundo.runtime.ExtMilieuRef t2 = jundo.runtime.Runtime.asgObjectObjectMember( tx.getObject() , "currentState" , t1 , null );
final jundo.runtime.ExtMilieuRef t3 = jundo.runtime.Runtime.asgObjectObjectMember( tx.getObject() , "undoStk" , t2 , null );
final verdantium.undo.pdx_UndoImpl_pdx_PairRef z = new verdantium.undo.pdx_UndoImpl_pdx_PairRef( in , t3 );
return( z );
}
	public static void pdx_initClassMembers( )
{
}

	static
{
pdx_initClassMembers();
}

	public verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_ObjectMemberAccess_pdx_getredoStk( final jundo.runtime.ExtMilieuRef mil )
{
return( (verdantium.undo.pdx_UndoNode_pdx_ObjectRef)( jundo.runtime.Runtime.getObjectObjectMember( this , "redoStk" , mil ) ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgredoStk( final jundo.runtime.ExtMilieuRef mil , final verdantium.undo.pdx_UndoNode_pdx_ObjectRef val )
{
return( jundo.runtime.Runtime.asgObjectObjectMember( this , "redoStk" , mil , val ) );
}
	public verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_ObjectMemberAccess_pdx_getcurrentState( final jundo.runtime.ExtMilieuRef mil )
{
return( (verdantium.undo.pdx_UndoNode_pdx_ObjectRef)( jundo.runtime.Runtime.getObjectObjectMember( this , "currentState" , mil ) ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgcurrentState( final jundo.runtime.ExtMilieuRef mil , final verdantium.undo.pdx_UndoNode_pdx_ObjectRef val )
{
return( jundo.runtime.Runtime.asgObjectObjectMember( this , "currentState" , mil , val ) );
}
	public verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_ObjectMemberAccess_pdx_getundoStk( final jundo.runtime.ExtMilieuRef mil )
{
return( (verdantium.undo.pdx_UndoNode_pdx_ObjectRef)( jundo.runtime.Runtime.getObjectObjectMember( this , "undoStk" , mil ) ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgundoStk( final jundo.runtime.ExtMilieuRef mil , final verdantium.undo.pdx_UndoNode_pdx_ObjectRef val )
{
return( jundo.runtime.Runtime.asgObjectObjectMember( this , "undoStk" , mil , val ) );
}
	public jundo.runtime.ExtMilieuRef pdxm_noteFileSave( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_9020 = ( this ).pdx_ObjectMemberAccess_pdx_asgredoStk( ( pdx_thismilieu ) , ( null ) );
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_9120 = ( this ).pdx_ObjectMemberAccess_pdx_getcurrentState( pdx_tmp_9020 );
final jundo.runtime.ExtMilieuRef pdx_tmp_9260 = pdx_tmp_9120.pdxm_setFileSavePoint( pdx_tmp_9020 , ( true ) );
return( ( pdx_tmp_9260 ) );
}
	public boolean pdxm_isRedoPossible( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_8700 = ( this ).pdx_ObjectMemberAccess_pdx_getredoStk( pdx_thismilieu );
final boolean pdx_tmp_8720 = jundo.runtime.Runtime.objectsNotShallowEqual( pdx_tmp_8700 , ( null ) );
return( pdx_tmp_8720 );
}
	public jundo.runtime.ExtMilieuRef pdxm_commitNonUndoableState( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final jundo.util.pdx_MilieuRef_pdx_ObjectRef  newState )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_3520 = ( this ).pdx_ObjectMemberAccess_pdx_asgundoStk( ( pdx_thismilieu ) , ( null ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_3640 = ( this ).pdx_ObjectMemberAccess_pdx_asgredoStk( pdx_tmp_3520 , ( null ) );
final verdantium.undo.pdx_UndoNode_pdx_PairRef pdx_tmp_4082 = verdantium.undo.pdx_UndoNode_pdx_ObjectRef.pdxm_allocate_UndoNode( ( pdx_tmp_3640 ) );
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_4080 = (verdantium.undo.pdx_UndoNode_pdx_ObjectRef)( pdx_tmp_4082.getObject() );
final jundo.runtime.ExtMilieuRef pdx_tmp_4081 = pdx_tmp_4082.getMilieu();
final jundo.runtime.ExtMilieuRef pdx_tmp_4400 = pdx_tmp_4080.pdxm_setState( pdx_tmp_4081 , ( newState ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_4440 = ( this ).pdx_ObjectMemberAccess_pdx_asgcurrentState( pdx_tmp_4400 , pdx_tmp_4080 );
return( ( pdx_tmp_4440 ) );
}
	public verdantium.undo.pdx_UndoIterator_pdx_PairRef pdxm_iterator( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_11660 = ( this ).pdx_ObjectMemberAccess_pdx_getcurrentState( pdx_thismilieu );
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_11700 = ( this ).pdx_ObjectMemberAccess_pdx_getundoStk( pdx_thismilieu );
final verdantium.undo.pdx_UndoIterator_pdx_PairRef pdx_tmp_11762 = verdantium.undo.pdx_UndoIterator_pdx_ObjectRef.pdxm_new_UndoIterator( pdx_thismilieu , pdx_tmp_11660 , pdx_tmp_11700 );
final verdantium.undo.pdx_UndoIterator_pdx_ObjectRef pdx_tmp_11760 = (verdantium.undo.pdx_UndoIterator_pdx_ObjectRef)( pdx_tmp_11762.getObject() );
final jundo.runtime.ExtMilieuRef pdx_tmp_11761 = pdx_tmp_11762.getMilieu();
return( new verdantium.undo.pdx_UndoIterator_pdx_PairRef( pdx_tmp_11760 , pdx_tmp_11761 ) );
}
	public jundo.runtime.ExtMilieuRef pdxm_performRedo( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_6920 = ( this ).pdx_ObjectMemberAccess_pdx_getredoStk( pdx_thismilieu );
final boolean pdx_tmp_6940 = jundo.runtime.Runtime.objectsNotShallowEqual( pdx_tmp_6920 , ( null ) );
jundo.runtime.ExtMilieuRef pdx_tmp_7160 =  null ;
if( pdx_tmp_6940 )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_7080 = ( this ).pdxm_performRedoComp( pdx_thismilieu );
pdx_tmp_7160 = pdx_tmp_7080;
}
else
{
pdx_tmp_7160 = ( pdx_thismilieu );
}
return( pdx_tmp_7160 );
}
	public java.lang.Object pdxm_getUndoDesc( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_10040 = ( this ).pdx_ObjectMemberAccess_pdx_getundoStk( pdx_thismilieu );
final boolean pdx_tmp_10060 = jundo.runtime.Runtime.objectsNotShallowEqual( pdx_tmp_10040 , ( null ) );
java.lang.Object pdx_tmp_10320 =  null ;
if( pdx_tmp_10060 )
{
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_10120 = ( this ).pdx_ObjectMemberAccess_pdx_getcurrentState( pdx_thismilieu );
final java.lang.Object pdx_tmp_10240 = pdx_tmp_10120.pdxm_getUndoDesc( pdx_thismilieu );
pdx_tmp_10320 = pdx_tmp_10240;
}
else
{
pdx_tmp_10320 = ( null );
}
return( pdx_tmp_10320 );
}
	public jundo.runtime.ExtMilieuRef pdxm_clearUndoMemory( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_11040 = ( this ).pdx_ObjectMemberAccess_pdx_asgundoStk( ( pdx_thismilieu ) , ( null ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_11160 = ( this ).pdx_ObjectMemberAccess_pdx_asgredoStk( pdx_tmp_11040 , ( null ) );
return( ( pdx_tmp_11160 ) );
}
	public jundo.runtime.ExtMilieuRef pdxm_getCurrentMilieu( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_760 = ( this ).pdx_ObjectMemberAccess_pdx_getcurrentState( ( pdx_thismilieu ) );
final jundo.util.pdx_MilieuRef_pdx_ObjectRef pdx_tmp_880 = pdx_tmp_760.pdxm_getState( ( pdx_thismilieu ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_1180 = pdx_tmp_880.pdxm_getVal( ( ( pdx_thismilieu ) ) );
return( pdx_tmp_1180 );
}
	public jundo.runtime.ExtMilieuRef pdxm_commitStateAction( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final jundo.util.pdx_MilieuRef_pdx_ObjectRef  newState , final java.lang.Object  undoDesc )
{
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_1720 = ( this ).pdx_ObjectMemberAccess_pdx_getcurrentState( ( pdx_thismilieu ) );
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_1840 = ( this ).pdx_ObjectMemberAccess_pdx_getundoStk( ( pdx_thismilieu ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_1900 = pdx_tmp_1720.pdxm_setNxt( ( pdx_thismilieu ) , pdx_tmp_1840 );
final jundo.runtime.ExtMilieuRef pdx_tmp_1940 = ( this ).pdx_ObjectMemberAccess_pdx_asgundoStk( pdx_tmp_1900 , pdx_tmp_1720 );
final verdantium.undo.pdx_UndoNode_pdx_PairRef pdx_tmp_2382 = verdantium.undo.pdx_UndoNode_pdx_ObjectRef.pdxm_allocate_UndoNode( ( pdx_tmp_1940 ) );
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_2380 = (verdantium.undo.pdx_UndoNode_pdx_ObjectRef)( pdx_tmp_2382.getObject() );
final jundo.runtime.ExtMilieuRef pdx_tmp_2381 = pdx_tmp_2382.getMilieu();
final jundo.runtime.ExtMilieuRef pdx_tmp_2700 = pdx_tmp_2380.pdxm_setState( pdx_tmp_2381 , ( newState ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_2860 = pdx_tmp_2380.pdxm_setUndoDesc( pdx_tmp_2700 , ( undoDesc ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_2900 = ( this ).pdx_ObjectMemberAccess_pdx_asgcurrentState( pdx_tmp_2860 , pdx_tmp_2380 );
final jundo.runtime.ExtMilieuRef pdx_tmp_3020 = ( this ).pdx_ObjectMemberAccess_pdx_asgredoStk( pdx_tmp_2900 , ( null ) );
return( ( pdx_tmp_3020 ) );
}
	public boolean pdxm_isUndoPossible( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_6680 = ( this ).pdx_ObjectMemberAccess_pdx_getundoStk( pdx_thismilieu );
final boolean pdx_tmp_6700 = jundo.runtime.Runtime.objectsNotShallowEqual( pdx_tmp_6680 , ( null ) );
return( pdx_tmp_6700 );
}
	public boolean pdxm_isFileSavePoint( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final boolean pdx_tmp_9640 = ( this ).pdxm_isUndoPossible( pdx_thismilieu );
boolean pdx_tmp_9860 =  false ;
if( pdx_tmp_9640 )
{
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_9660 = ( this ).pdx_ObjectMemberAccess_pdx_getcurrentState( pdx_thismilieu );
final boolean pdx_tmp_9780 = pdx_tmp_9660.pdxm_isFileSavePoint( pdx_thismilieu );
pdx_tmp_9860 = pdx_tmp_9780;
}
else
{
pdx_tmp_9860 = ( false );
}
return( pdx_tmp_9860 );
}
	protected jundo.runtime.ExtMilieuRef pdxm_performRedoComp( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_7540 = ( this ).pdx_ObjectMemberAccess_pdx_getcurrentState( ( pdx_thismilieu ) );
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_7900 = ( this ).pdx_ObjectMemberAccess_pdx_getundoStk( ( ( pdx_thismilieu ) ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_7960 = pdx_tmp_7540.pdxm_setNxt( ( ( pdx_thismilieu ) ) , pdx_tmp_7900 );
final jundo.runtime.ExtMilieuRef pdx_tmp_8000 = ( this ).pdx_ObjectMemberAccess_pdx_asgundoStk( pdx_tmp_7960 , pdx_tmp_7540 );
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_8140 = ( this ).pdx_ObjectMemberAccess_pdx_getredoStk( pdx_tmp_8000 );
final jundo.runtime.ExtMilieuRef pdx_tmp_8120 = ( this ).pdx_ObjectMemberAccess_pdx_asgcurrentState( pdx_tmp_8000 , pdx_tmp_8140 );
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_8260 = ( this ).pdx_ObjectMemberAccess_pdx_getredoStk( pdx_tmp_8120 );
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_8380 = pdx_tmp_8260.pdxm_getNxt( pdx_tmp_8120 );
final jundo.runtime.ExtMilieuRef pdx_tmp_8240 = ( this ).pdx_ObjectMemberAccess_pdx_asgredoStk( pdx_tmp_8120 , pdx_tmp_8380 );
return( ( pdx_tmp_8240 ) );
}
	protected jundo.runtime.ExtMilieuRef pdxm_performUndoComp( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_5640 = ( this ).pdx_ObjectMemberAccess_pdx_getcurrentState( ( pdx_thismilieu ) );
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_5720 = ( this ).pdx_ObjectMemberAccess_pdx_getredoStk( ( pdx_thismilieu ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_5780 = pdx_tmp_5640.pdxm_setNxt( ( pdx_thismilieu ) , pdx_tmp_5720 );
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_5840 = ( this ).pdx_ObjectMemberAccess_pdx_getcurrentState( pdx_tmp_5780 );
final jundo.runtime.ExtMilieuRef pdx_tmp_5820 = ( this ).pdx_ObjectMemberAccess_pdx_asgredoStk( pdx_tmp_5780 , pdx_tmp_5840 );
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_5960 = ( this ).pdx_ObjectMemberAccess_pdx_getundoStk( pdx_tmp_5820 );
final jundo.runtime.ExtMilieuRef pdx_tmp_5940 = ( this ).pdx_ObjectMemberAccess_pdx_asgcurrentState( pdx_tmp_5820 , pdx_tmp_5960 );
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_6080 = ( this ).pdx_ObjectMemberAccess_pdx_getundoStk( pdx_tmp_5940 );
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_6200 = pdx_tmp_6080.pdxm_getNxt( pdx_tmp_5940 );
final jundo.runtime.ExtMilieuRef pdx_tmp_6060 = ( this ).pdx_ObjectMemberAccess_pdx_asgundoStk( pdx_tmp_5940 , pdx_tmp_6200 );
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_6260 = ( this ).pdx_ObjectMemberAccess_pdx_getcurrentState( pdx_tmp_6060 );
final jundo.runtime.ExtMilieuRef pdx_tmp_6400 = pdx_tmp_6260.pdxm_setNxt( pdx_tmp_6060 , ( null ) );
return( ( pdx_tmp_6400 ) );
}
	public jundo.runtime.ExtMilieuRef pdxm_commitOverlay( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final jundo.util.pdx_MilieuRef_pdx_ObjectRef  newState )
{
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_4840 = ( this ).pdx_ObjectMemberAccess_pdx_getcurrentState( pdx_thismilieu );
final jundo.runtime.ExtMilieuRef pdx_tmp_4980 = pdx_tmp_4840.pdxm_setState( pdx_thismilieu , ( newState ) );
return( pdx_tmp_4980 );
}
	public java.lang.Object pdxm_getRedoDesc( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_10500 = ( this ).pdx_ObjectMemberAccess_pdx_getredoStk( pdx_thismilieu );
final boolean pdx_tmp_10520 = jundo.runtime.Runtime.objectsNotShallowEqual( pdx_tmp_10500 , ( null ) );
java.lang.Object pdx_tmp_10780 =  null ;
if( pdx_tmp_10520 )
{
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_10580 = ( this ).pdx_ObjectMemberAccess_pdx_getredoStk( pdx_thismilieu );
final java.lang.Object pdx_tmp_10700 = pdx_tmp_10580.pdxm_getUndoDesc( pdx_thismilieu );
pdx_tmp_10780 = pdx_tmp_10700;
}
else
{
pdx_tmp_10780 = ( null );
}
return( pdx_tmp_10780 );
}
	public jundo.runtime.ExtMilieuRef pdxm_performUndo( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_5160 = ( this ).pdx_ObjectMemberAccess_pdx_getundoStk( pdx_thismilieu );
final boolean pdx_tmp_5180 = jundo.runtime.Runtime.objectsNotShallowEqual( pdx_tmp_5160 , ( null ) );
jundo.runtime.ExtMilieuRef pdx_tmp_5400 =  null ;
if( pdx_tmp_5180 )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_5320 = ( this ).pdxm_performUndoComp( pdx_thismilieu );
pdx_tmp_5400 = pdx_tmp_5320;
}
else
{
pdx_tmp_5400 = ( pdx_thismilieu );
}
return( pdx_tmp_5400 );
}
	}

