
/**************
* This source file was generated by JUndo compiler version 051002A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See http://sourceforge.net/projects/jundo
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.  See the associated .JUndo file for license and
* copyright information.
* This File Generated : Fri Oct 28 21:31:55 MDT 2005
* From Input File : UndoIterator.JUndo
**************/

package verdantium.undo;

class pdx_UndoIterator_pdx_ObjectRef extends jundo.runtime.ExtObjectRef implements jundo.util.pdx_Iterator_pdx_ObjectRef
	{
protected pdx_UndoIterator_pdx_ObjectRef( jundo.runtime.KeyRef Key )
{
super( Key );
}

public static verdantium.undo.pdx_UndoIterator_pdx_PairRef createOID_UndoIterator( jundo.runtime.ExtMilieuRef InMil )
{
jundo.runtime.ExtMilieuRef NewMil = jundo.runtime.Runtime.createOIDmilieu( InMil );
int NewID = NewMil.getMaxID();
jundo.runtime.KeyRef MyKey = jundo.runtime.Runtime.getKeyRef( NewID );
pdx_UndoIterator_pdx_ObjectRef NewObj = 
	new pdx_UndoIterator_pdx_ObjectRef( MyKey );
verdantium.undo.pdx_UndoIterator_pdx_PairRef ret = new verdantium.undo.pdx_UndoIterator_pdx_PairRef( NewObj , NewMil );
return( ret );
}
	public static verdantium.undo.pdx_UndoIterator_pdx_PairRef pdxm_new_UndoIterator( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final verdantium.undo.pdx_UndoNode_pdx_ObjectRef  curNode , final verdantium.undo.pdx_UndoNode_pdx_ObjectRef  node )
{
final verdantium.undo.pdx_UndoIterator_pdx_PairRef pdx_tmp_3142 = verdantium.undo.pdx_UndoIterator_pdx_ObjectRef.pdxm_allocate_UndoIterator( ( pdx_thismilieu ) );
final verdantium.undo.pdx_UndoIterator_pdx_ObjectRef pdx_tmp_3140 = (verdantium.undo.pdx_UndoIterator_pdx_ObjectRef)( pdx_tmp_3142.getObject() );
final jundo.runtime.ExtMilieuRef pdx_tmp_3141 = pdx_tmp_3142.getMilieu();
final jundo.runtime.ExtMilieuRef pdx_tmp_3320 = pdx_tmp_3140.pdx_ObjectMemberAccess_pdx_asgcurNode( pdx_tmp_3141 , ( curNode ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_3560 = pdx_tmp_3140.pdx_ObjectMemberAccess_pdx_asgnode( pdx_tmp_3320 , ( node ) );
return( new verdantium.undo.pdx_UndoIterator_pdx_PairRef( pdx_tmp_3140 , ( pdx_tmp_3560 ) ) );
}
	public static verdantium.undo.pdx_UndoIterator_pdx_PairRef pdxm_allocate_UndoIterator( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.undo.pdx_UndoIterator_pdx_PairRef t1 = pdx_UndoIterator_pdx_ObjectRef.createOID_UndoIterator( pdx_thismilieu );
final verdantium.undo.pdx_UndoIterator_pdx_PairRef t2 = pdx_zero( t1.getMilieu() , (verdantium.undo.pdx_UndoIterator_pdx_ObjectRef)( t1.getObject() ) );

return( t2 );
}
	public static verdantium.undo.pdx_UndoIterator_pdx_PairRef pdx_zero( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final verdantium.undo.pdx_UndoIterator_pdx_ObjectRef in )
{
final verdantium.undo.pdx_UndoIterator_pdx_PairRef tx = new verdantium.undo.pdx_UndoIterator_pdx_PairRef( in , pdx_thismilieu );
final jundo.runtime.ExtMilieuRef t0 = tx.getMilieu();
final jundo.runtime.ExtMilieuRef t1 = jundo.runtime.Runtime.asgObjectObjectMember( tx.getObject() , "curNode" , t0 , null );
final jundo.runtime.ExtMilieuRef t2 = jundo.runtime.Runtime.asgObjectObjectMember( tx.getObject() , "node" , t1 , null );
final verdantium.undo.pdx_UndoIterator_pdx_PairRef z = new verdantium.undo.pdx_UndoIterator_pdx_PairRef( in , t2 );
return( z );
}
	public static void pdx_initClassMembers( )
{
}

	static
{
pdx_initClassMembers();
}

	public verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_ObjectMemberAccess_pdx_getcurNode( final jundo.runtime.ExtMilieuRef mil )
{
return( (verdantium.undo.pdx_UndoNode_pdx_ObjectRef)( jundo.runtime.Runtime.getObjectObjectMember( this , "curNode" , mil ) ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgcurNode( final jundo.runtime.ExtMilieuRef mil , final verdantium.undo.pdx_UndoNode_pdx_ObjectRef val )
{
return( jundo.runtime.Runtime.asgObjectObjectMember( this , "curNode" , mil , val ) );
}
	public verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_ObjectMemberAccess_pdx_getnode( final jundo.runtime.ExtMilieuRef mil )
{
return( (verdantium.undo.pdx_UndoNode_pdx_ObjectRef)( jundo.runtime.Runtime.getObjectObjectMember( this , "node" , mil ) ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgnode( final jundo.runtime.ExtMilieuRef mil , final verdantium.undo.pdx_UndoNode_pdx_ObjectRef val )
{
return( jundo.runtime.Runtime.asgObjectObjectMember( this , "node" , mil , val ) );
}
	public jundo.runtime.ExtBooleanPair pdxm_hasNext( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_720 = ( this ).pdx_ObjectMemberAccess_pdx_getnode( pdx_thismilieu );
final boolean pdx_tmp_740 = jundo.runtime.Runtime.objectsNotShallowEqual( pdx_tmp_720 , ( null ) );
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_840 = ( this ).pdx_ObjectMemberAccess_pdx_getcurNode( pdx_thismilieu );
final boolean pdx_tmp_860 = jundo.runtime.Runtime.objectsNotShallowEqual( pdx_tmp_840 , ( null ) );
final boolean pdx_tmp_800 = pdx_tmp_740 || pdx_tmp_860;
return( new jundo.runtime.ExtBooleanPair( pdx_tmp_800 , ( pdx_thismilieu ) ) );
}
	public jundo.runtime.IExtPair pdxm_next( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_1240 = ( this ).pdx_ObjectMemberAccess_pdx_getcurNode( pdx_thismilieu );
final boolean pdx_tmp_1260 = jundo.runtime.Runtime.objectsNotShallowEqual( pdx_tmp_1240 , ( null ) );
jundo.runtime.IExtObjectRef pdx_tmp_2480 =  null ;
jundo.runtime.ExtMilieuRef pdx_tmp_2481 =  null ;
if( pdx_tmp_1260 )
{
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_1460 = ( this ).pdx_ObjectMemberAccess_pdx_getcurNode( ( pdx_thismilieu ) );
final jundo.runtime.IExtObjectRef pdx_tmp_4000 = pdx_tmp_1460;
final jundo.runtime.ExtMilieuRef pdx_tmp_1520 = ( this ).pdx_ObjectMemberAccess_pdx_asgcurNode( ( pdx_thismilieu ) , ( null ) );
pdx_tmp_2480 = pdx_tmp_4000;
pdx_tmp_2481 = ( pdx_tmp_1520 );
}
else
{
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_1980 = ( this ).pdx_ObjectMemberAccess_pdx_getnode( ( pdx_thismilieu ) );
final jundo.runtime.IExtObjectRef pdx_tmp_4020 = pdx_tmp_1980;
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_2060 = ( this ).pdx_ObjectMemberAccess_pdx_getnode( ( pdx_thismilieu ) );
final verdantium.undo.pdx_UndoNode_pdx_ObjectRef pdx_tmp_2180 = pdx_tmp_2060.pdxm_getNxt( ( pdx_thismilieu ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_2040 = ( this ).pdx_ObjectMemberAccess_pdx_asgnode( ( pdx_thismilieu ) , pdx_tmp_2180 );
pdx_tmp_2480 = pdx_tmp_4020;
pdx_tmp_2481 = ( pdx_tmp_2040 );
}
return( new jundo.runtime.ExtPair( pdx_tmp_2480 , pdx_tmp_2481 ) );
}
	}

