
/**************
* This source file was generated by JUndo compiler version 050827A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See [put web site address here]
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.
* This File Generated : Tue Aug 30 17:29:49 MDT 2005
* From Input File : GradientPaneModel.JUndo
**************/

package verdantium.demo.gradientpane;

class pdx_GradientPaneModel_pdx_ObjectRef extends jundo.runtime.ExtObjectRef
	{
protected pdx_GradientPaneModel_pdx_ObjectRef(  jundo.runtime.KeyRef Key )
{
super( Key );
}

public static verdantium.demo.gradientpane.pdx_GradientPaneModel_pdx_PairRef createOID_GradientPaneModel( jundo.runtime.ExtMilieuRef InMil )
{
jundo.runtime.ExtMilieuRef NewMil = jundo.runtime.Runtime.createOIDmilieu( InMil );
int NewID = NewMil.getMaxID();
jundo.runtime.KeyRef MyKey = jundo.runtime.Runtime.getKeyRef( NewID );
pdx_GradientPaneModel_pdx_ObjectRef NewObj = 
	new pdx_GradientPaneModel_pdx_ObjectRef( MyKey );
verdantium.demo.gradientpane.pdx_GradientPaneModel_pdx_PairRef ret = new verdantium.demo.gradientpane.pdx_GradientPaneModel_pdx_PairRef( NewObj , NewMil );
return( ret );
}
	public static verdantium.demo.gradientpane.pdx_GradientPaneModel_pdx_PairRef pdxm_new_GradientPaneModel( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  coa , final java.lang.Object  cob , final boolean  vertical , final boolean  onlyDesignerEdits )
{
final verdantium.demo.gradientpane.pdx_GradientPaneModel_pdx_PairRef pdx_tmp_3142 = verdantium.demo.gradientpane.pdx_GradientPaneModel_pdx_ObjectRef.pdxm_allocate_GradientPaneModel( ( pdx_thismilieu ) );
final verdantium.demo.gradientpane.pdx_GradientPaneModel_pdx_ObjectRef pdx_tmp_3140 = (verdantium.demo.gradientpane.pdx_GradientPaneModel_pdx_ObjectRef)( pdx_tmp_3142.getObject() );
final jundo.runtime.ExtMilieuRef pdx_tmp_3141 = pdx_tmp_3142.getMilieu();
final jundo.runtime.ExtMilieuRef pdx_tmp_3460 = pdx_tmp_3140.pdxm_setColorA( pdx_tmp_3141 , ( coa ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_3620 = pdx_tmp_3140.pdxm_setColorB( pdx_tmp_3460 , ( cob ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_3780 = pdx_tmp_3140.pdxm_setVertical( pdx_tmp_3620 , ( vertical ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_3940 = pdx_tmp_3140.pdxm_setOnlyDesignerEdits( pdx_tmp_3780 , ( onlyDesignerEdits ) );
return( new verdantium.demo.gradientpane.pdx_GradientPaneModel_pdx_PairRef( pdx_tmp_3140 , ( pdx_tmp_3940 ) ) );
}
	public static verdantium.demo.gradientpane.pdx_GradientPaneModel_pdx_PairRef pdxm_allocate_GradientPaneModel( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.demo.gradientpane.pdx_GradientPaneModel_pdx_PairRef t1 = pdx_GradientPaneModel_pdx_ObjectRef.createOID_GradientPaneModel( pdx_thismilieu );
final verdantium.demo.gradientpane.pdx_GradientPaneModel_pdx_PairRef t2 = pdx_zero( t1.getMilieu() , (verdantium.demo.gradientpane.pdx_GradientPaneModel_pdx_ObjectRef)( t1.getObject() ) );

return( t2 );
}
	public static verdantium.demo.gradientpane.pdx_GradientPaneModel_pdx_PairRef pdx_zero( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final verdantium.demo.gradientpane.pdx_GradientPaneModel_pdx_ObjectRef in )
{
final verdantium.demo.gradientpane.pdx_GradientPaneModel_pdx_PairRef tx = new verdantium.demo.gradientpane.pdx_GradientPaneModel_pdx_PairRef( in , pdx_thismilieu );
final jundo.runtime.ExtMilieuRef t0 = tx.getMilieu();
final jundo.runtime.ExtMilieuRef t1 = jundo.runtime.Runtime.asgBooleanObjectMember( tx.getObject() , "vertical" , t0 , false );
final jundo.runtime.ExtMilieuRef t2 = jundo.runtime.Runtime.asgBooleanObjectMember( tx.getObject() , "onlyDesignerEdits" , t1 , false );
final jundo.runtime.ExtMilieuRef t3 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "cob" , t2 , null );
final jundo.runtime.ExtMilieuRef t4 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "coa" , t3 , null );
final verdantium.demo.gradientpane.pdx_GradientPaneModel_pdx_PairRef z = new verdantium.demo.gradientpane.pdx_GradientPaneModel_pdx_PairRef( in , t4 );
return( z );
}
	public static void pdx_initClassMembers( )
{
}

	static
{
pdx_initClassMembers();
}

	public boolean pdx_ObjectMemberAccess_pdx_getvertical( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getBooleanObjectMember( this , "vertical" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgvertical( final jundo.runtime.ExtMilieuRef mil , final boolean val )
{
return( jundo.runtime.Runtime.asgBooleanObjectMember( this , "vertical" , mil , val ) );
}
	public boolean pdx_ObjectMemberAccess_pdx_getonlyDesignerEdits( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getBooleanObjectMember( this , "onlyDesignerEdits" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgonlyDesignerEdits( final jundo.runtime.ExtMilieuRef mil , final boolean val )
{
return( jundo.runtime.Runtime.asgBooleanObjectMember( this , "onlyDesignerEdits" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getcob( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "cob" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgcob( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "cob" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getcoa( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "coa" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgcoa( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "coa" , mil , val ) );
}
	public java.lang.Object pdxm_getColorB( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_1080 = ( this ).pdx_ObjectMemberAccess_pdx_getcob( pdx_thismilieu );
return( pdx_tmp_1080 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setVertical( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final boolean  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_1800 = ( this ).pdx_ObjectMemberAccess_pdx_asgvertical( pdx_thismilieu , ( in ) );
return( pdx_tmp_1800 );
}
	public boolean pdxm_isOnlyDesignerEdits( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final boolean pdx_tmp_2040 = ( this ).pdx_ObjectMemberAccess_pdx_getonlyDesignerEdits( pdx_thismilieu );
return( pdx_tmp_2040 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setColorB( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_1320 = ( this ).pdx_ObjectMemberAccess_pdx_asgcob( pdx_thismilieu , ( in ) );
return( pdx_tmp_1320 );
}
	public boolean pdxm_isVertical( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final boolean pdx_tmp_1560 = ( this ).pdx_ObjectMemberAccess_pdx_getvertical( pdx_thismilieu );
return( pdx_tmp_1560 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setOnlyDesignerEdits( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final boolean  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_2280 = ( this ).pdx_ObjectMemberAccess_pdx_asgonlyDesignerEdits( pdx_thismilieu , ( in ) );
return( pdx_tmp_2280 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setColorA( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_840 = ( this ).pdx_ObjectMemberAccess_pdx_asgcoa( pdx_thismilieu , ( in ) );
return( pdx_tmp_840 );
}
	public java.lang.Object pdxm_getColorA( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_600 = ( this ).pdx_ObjectMemberAccess_pdx_getcoa( pdx_thismilieu );
return( pdx_tmp_600 );
}
	}

