
/**************
* This source file was generated by JUndo compiler version 050827A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See [put web site address here]
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.
* This File Generated : Tue Aug 30 17:29:50 MDT 2005
* From Input File : GradientPaneModel.JUndo
**************/

package verdantium.demo.gradientpane;

class pdx_GradientPaneModel_pdx_PairRef extends jundo.runtime.ExtPair
	{
public pdx_GradientPaneModel_pdx_PairRef( pdx_GradientPaneModel_pdx_ObjectRef obj , jundo.runtime.ExtMilieuRef mil )
{
super( obj , mil );
}
	}

