
/**************
* This source file was generated by JUndo compiler version 051002A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See http://sourceforge.net/projects/jundo
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.  See the associated .JUndo file for license and
* copyright information.
* This File Generated : Sun Dec 04 06:22:49 MST 2005
* From Input File : PageWelderModel.JUndo
**************/

package verdantium.pagewelder;

class pdx_PageWelderModel_pdx_PairRef extends jundo.runtime.ExtPair
	{
public pdx_PageWelderModel_pdx_PairRef( pdx_PageWelderModel_pdx_ObjectRef obj , jundo.runtime.ExtMilieuRef mil )
{
super( obj , mil );
}
	}

