
/**************
* This source file was generated by JUndo compiler version 051002A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See http://sourceforge.net/projects/jundo
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.  See the associated .JUndo file for license and
* copyright information.
* This File Generated : Sun Dec 04 06:22:47 MST 2005
* From Input File : PageWelderModel.JUndo
**************/

package verdantium.pagewelder;

class pdx_PageWelderModel_pdx_ObjectRef extends jundo.runtime.ExtObjectRef
	{
protected pdx_PageWelderModel_pdx_ObjectRef( jundo.runtime.KeyRef Key )
{
super( Key );
}

public static verdantium.pagewelder.pdx_PageWelderModel_pdx_PairRef createOID_PageWelderModel( jundo.runtime.ExtMilieuRef InMil )
{
jundo.runtime.ExtMilieuRef NewMil = jundo.runtime.Runtime.createOIDmilieu( InMil );
int NewID = NewMil.getMaxID();
jundo.runtime.KeyRef MyKey = jundo.runtime.Runtime.getKeyRef( NewID );
pdx_PageWelderModel_pdx_ObjectRef NewObj = 
	new pdx_PageWelderModel_pdx_ObjectRef( MyKey );
verdantium.pagewelder.pdx_PageWelderModel_pdx_PairRef ret = new verdantium.pagewelder.pdx_PageWelderModel_pdx_PairRef( NewObj , NewMil );
return( ret );
}
	public static verdantium.pagewelder.pdx_PageWelderModel_pdx_PairRef pdxm_new_PageWelderModel( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.pagewelder.pdx_PageWelderModel_pdx_PairRef pdx_tmp_3482 = verdantium.pagewelder.pdx_PageWelderModel_pdx_ObjectRef.pdxm_allocate_PageWelderModel( ( pdx_thismilieu ) );
final verdantium.pagewelder.pdx_PageWelderModel_pdx_ObjectRef pdx_tmp_3480 = (verdantium.pagewelder.pdx_PageWelderModel_pdx_ObjectRef)( pdx_tmp_3482.getObject() );
final jundo.runtime.ExtMilieuRef pdx_tmp_3481 = pdx_tmp_3482.getMilieu();
final int pdx_tmp_3740 = 0;
final jundo.runtime.ExtMilieuRef pdx_tmp_3800 = pdx_tmp_3480.pdxm_setCurrentIndex( pdx_tmp_3481 , pdx_tmp_3740 );
final int pdx_tmp_3900 = 0;
final jundo.runtime.ExtMilieuRef pdx_tmp_3960 = pdx_tmp_3480.pdxm_setNumCards( pdx_tmp_3800 , pdx_tmp_3900 );
final int pdx_tmp_4080 = 1;
final int pdx_tmp_4060 = - pdx_tmp_4080;
final jundo.runtime.ExtMilieuRef pdx_tmp_4140 = pdx_tmp_3480.pdxm_setPrevIndex( pdx_tmp_3960 , pdx_tmp_4060 );
return( new verdantium.pagewelder.pdx_PageWelderModel_pdx_PairRef( pdx_tmp_3480 , ( pdx_tmp_4140 ) ) );
}
	public static verdantium.pagewelder.pdx_PageWelderModel_pdx_PairRef pdxm_allocate_PageWelderModel( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.pagewelder.pdx_PageWelderModel_pdx_PairRef t1 = pdx_PageWelderModel_pdx_ObjectRef.createOID_PageWelderModel( pdx_thismilieu );
final verdantium.pagewelder.pdx_PageWelderModel_pdx_PairRef t2 = pdx_zero( t1.getMilieu() , (verdantium.pagewelder.pdx_PageWelderModel_pdx_ObjectRef)( t1.getObject() ) );

return( t2 );
}
	public static verdantium.pagewelder.pdx_PageWelderModel_pdx_PairRef pdx_zero( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final verdantium.pagewelder.pdx_PageWelderModel_pdx_ObjectRef in )
{
final verdantium.pagewelder.pdx_PageWelderModel_pdx_PairRef tx = new verdantium.pagewelder.pdx_PageWelderModel_pdx_PairRef( in , pdx_thismilieu );
final jundo.runtime.ExtMilieuRef t0 = tx.getMilieu();
final jundo.runtime.ExtMilieuRef t1 = jundo.runtime.Runtime.asgIntObjectMember( tx.getObject() , "numCards" , t0 , 0 );
final jundo.runtime.ExtMilieuRef t2 = jundo.runtime.Runtime.asgIntObjectMember( tx.getObject() , "prevIndex" , t1 , 0 );
final jundo.runtime.ExtMilieuRef t3 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "bkgndTemplateTrans" , t2 , null );
final jundo.runtime.ExtMilieuRef t4 = jundo.runtime.Runtime.asgIntObjectMember( tx.getObject() , "currentIndex" , t3 , 0 );
final jundo.runtime.ExtMilieuRef t5 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "bkgndTemplate" , t4 , null );
final verdantium.pagewelder.pdx_PageWelderModel_pdx_PairRef z = new verdantium.pagewelder.pdx_PageWelderModel_pdx_PairRef( in , t5 );
return( z );
}
	public static void pdx_initClassMembers( )
{
}

	static
{
pdx_initClassMembers();
}

	public int pdx_ObjectMemberAccess_pdx_getnumCards( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getIntObjectMember( this , "numCards" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgnumCards( final jundo.runtime.ExtMilieuRef mil , final int val )
{
return( jundo.runtime.Runtime.asgIntObjectMember( this , "numCards" , mil , val ) );
}
	public int pdx_ObjectMemberAccess_pdx_getprevIndex( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getIntObjectMember( this , "prevIndex" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgprevIndex( final jundo.runtime.ExtMilieuRef mil , final int val )
{
return( jundo.runtime.Runtime.asgIntObjectMember( this , "prevIndex" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getbkgndTemplateTrans( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "bkgndTemplateTrans" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgbkgndTemplateTrans( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "bkgndTemplateTrans" , mil , val ) );
}
	public int pdx_ObjectMemberAccess_pdx_getcurrentIndex( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getIntObjectMember( this , "currentIndex" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgcurrentIndex( final jundo.runtime.ExtMilieuRef mil , final int val )
{
return( jundo.runtime.Runtime.asgIntObjectMember( this , "currentIndex" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getbkgndTemplate( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "bkgndTemplate" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgbkgndTemplate( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "bkgndTemplate" , mil , val ) );
}
	public int pdxm_getPrevIndex( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final int pdx_tmp_1640 = ( this ).pdx_ObjectMemberAccess_pdx_getprevIndex( pdx_thismilieu );
return( pdx_tmp_1640 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setNumCards( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final int  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_1400 = ( this ).pdx_ObjectMemberAccess_pdx_asgnumCards( pdx_thismilieu , ( in ) );
return( pdx_tmp_1400 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setPrevIndex( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final int  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_1880 = ( this ).pdx_ObjectMemberAccess_pdx_asgprevIndex( pdx_thismilieu , ( in ) );
return( pdx_tmp_1880 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setBkgndTemplate( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_2360 = ( this ).pdx_ObjectMemberAccess_pdx_asgbkgndTemplate( pdx_thismilieu , ( in ) );
return( pdx_tmp_2360 );
}
	public int pdxm_getNumCards( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final int pdx_tmp_1160 = ( this ).pdx_ObjectMemberAccess_pdx_getnumCards( pdx_thismilieu );
return( pdx_tmp_1160 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setCurrentIndex( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final int  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_920 = ( this ).pdx_ObjectMemberAccess_pdx_asgcurrentIndex( pdx_thismilieu , ( in ) );
return( pdx_tmp_920 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setBkgndTemplateTrans( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_2840 = ( this ).pdx_ObjectMemberAccess_pdx_asgbkgndTemplateTrans( pdx_thismilieu , ( in ) );
return( pdx_tmp_2840 );
}
	public java.lang.Object pdxm_getBkgndTemplate( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_2120 = ( this ).pdx_ObjectMemberAccess_pdx_getbkgndTemplate( pdx_thismilieu );
return( pdx_tmp_2120 );
}
	public int pdxm_getCurrentIndex( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final int pdx_tmp_680 = ( this ).pdx_ObjectMemberAccess_pdx_getcurrentIndex( pdx_thismilieu );
return( pdx_tmp_680 );
}
	public java.lang.Object pdxm_getBkgndTemplateTrans( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_2600 = ( this ).pdx_ObjectMemberAccess_pdx_getbkgndTemplateTrans( pdx_thismilieu );
return( pdx_tmp_2600 );
}
	}

