
/**************
* This source file was generated by JUndo compiler version 070726A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See http://sourceforge.net/projects/jundo
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.  See the associated .JUndo file for license and
* copyright information.
* This File Generated : Sat Aug 04 10:53:57 MDT 2007
* From Input File : DrawingObject.JUndo
**************/

package verdantium.standard;

public class pdx_DrawingObject_pdx_PairRef extends umeta.pdx_Meta_pdx_PairRef implements umeta.pdx_Versionable_pdx_PairRef
	{
public pdx_DrawingObject_pdx_PairRef( pdx_DrawingObject_pdx_ObjectRef obj , jundo.runtime.ExtMilieuRef mil )
{
super( obj , mil );
}
	}

