
/**************
* This source file was generated by JUndo compiler version 070726A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See http://sourceforge.net/projects/jundo
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.  See the associated .JUndo file for license and
* copyright information.
* This File Generated : Thu Aug 02 20:55:37 MDT 2007
* From Input File : DrawingRectangularObjectBase.JUndo
**************/

package verdantium.standard;

public abstract class pdx_DrawingRectangularObjectBase_pdx_ObjectRef extends verdantium.standard.pdx_DrawingObject_pdx_ObjectRef
	{
protected pdx_DrawingRectangularObjectBase_pdx_ObjectRef( jundo.runtime.KeyRef Key )
{
super( Key );
}

	public static verdantium.standard.pdx_DrawingRectangularObjectBase_pdx_PairRef pdx_zero( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final verdantium.standard.pdx_DrawingRectangularObjectBase_pdx_ObjectRef in )
{
final verdantium.standard.pdx_DrawingRectangularObjectBase_pdx_PairRef tx = new verdantium.standard.pdx_DrawingRectangularObjectBase_pdx_PairRef( in , pdx_thismilieu );
final jundo.runtime.ExtMilieuRef t0 = tx.getMilieu();
final jundo.runtime.ExtMilieuRef t1 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "myRect" , t0 , null );
final jundo.runtime.ExtMilieuRef t2 = jundo.runtime.Runtime.asgDoubleObjectMember( tx.getObject() , "basicStrokeWidth" , t1 , 0 );
final jundo.runtime.ExtMilieuRef t3 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "myRct" , t2 , null );
final jundo.runtime.ExtMilieuRef t4 = jundo.runtime.Runtime.asgIntObjectMember( tx.getObject() , "renderingMode" , t3 , 0 );
final jundo.runtime.ExtMilieuRef t5 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "myStroke" , t4 , null );
final jundo.runtime.ExtMilieuRef t6 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "myEll" , t5 , null );
final jundo.runtime.ExtMilieuRef t7 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "lineColor" , t6 , null );
final jundo.runtime.ExtMilieuRef t8 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "myRound" , t7 , null );
final jundo.runtime.ExtMilieuRef t9 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "myLine" , t8 , null );
final jundo.runtime.ExtMilieuRef t10 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "fillColor" , t9 , null );
final verdantium.standard.pdx_DrawingRectangularObjectBase_pdx_PairRef z = new verdantium.standard.pdx_DrawingRectangularObjectBase_pdx_PairRef( in , t10 );
return( z );
}
	public static void pdx_initClassMembers( )
{
}

	static
{
pdx_initClassMembers();
}

	public java.lang.Object pdx_ObjectMemberAccess_pdx_getmyRect( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "myRect" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgmyRect( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "myRect" , mil , val ) );
}
	public double pdx_ObjectMemberAccess_pdx_getbasicStrokeWidth( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getDoubleObjectMember( this , "basicStrokeWidth" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgbasicStrokeWidth( final jundo.runtime.ExtMilieuRef mil , final double val )
{
return( jundo.runtime.Runtime.asgDoubleObjectMember( this , "basicStrokeWidth" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getmyRct( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "myRct" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgmyRct( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "myRct" , mil , val ) );
}
	public int pdx_ObjectMemberAccess_pdx_getrenderingMode( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getIntObjectMember( this , "renderingMode" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgrenderingMode( final jundo.runtime.ExtMilieuRef mil , final int val )
{
return( jundo.runtime.Runtime.asgIntObjectMember( this , "renderingMode" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getmyStroke( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "myStroke" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgmyStroke( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "myStroke" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getmyEll( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "myEll" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgmyEll( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "myEll" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getlineColor( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "lineColor" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asglineColor( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "lineColor" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getmyRound( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "myRound" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgmyRound( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "myRound" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getmyLine( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "myLine" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgmyLine( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "myLine" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getfillColor( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "fillColor" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgfillColor( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "fillColor" , mil , val ) );
}
	public java.lang.Object pdxm_getMyRect( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_2220 = ( this ).pdx_ObjectMemberAccess_pdx_getmyRect( pdx_thismilieu );
return( pdx_tmp_2220 );
}
	public java.lang.Object pdxm_getMyRound( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_4460 = ( this ).pdx_ObjectMemberAccess_pdx_getmyRound( pdx_thismilieu );
return( pdx_tmp_4460 );
}
	public java.lang.Object pdxm_getMyLine( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_5580 = ( this ).pdx_ObjectMemberAccess_pdx_getmyLine( pdx_thismilieu );
return( pdx_tmp_5580 );
}
	public java.lang.Object pdxm_getFillColor( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_1660 = ( this ).pdx_ObjectMemberAccess_pdx_getfillColor( pdx_thismilieu );
return( pdx_tmp_1660 );
}
	public int pdxm_getRenderingMode( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final int pdx_tmp_540 = ( this ).pdx_ObjectMemberAccess_pdx_getrenderingMode( pdx_thismilieu );
return( pdx_tmp_540 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setMyEll( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_4140 = ( this ).pdx_ObjectMemberAccess_pdx_asgmyEll( pdx_thismilieu , ( in ) );
return( pdx_tmp_4140 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setFillColor( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_1900 = ( this ).pdx_ObjectMemberAccess_pdx_asgfillColor( pdx_thismilieu , ( in ) );
return( pdx_tmp_1900 );
}
	public java.lang.Object pdxm_getLineColor( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_1100 = ( this ).pdx_ObjectMemberAccess_pdx_getlineColor( pdx_thismilieu );
return( pdx_tmp_1100 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setMyStroke( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_3580 = ( this ).pdx_ObjectMemberAccess_pdx_asgmyStroke( pdx_thismilieu , ( in ) );
return( pdx_tmp_3580 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setMyRect( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_2460 = ( this ).pdx_ObjectMemberAccess_pdx_asgmyRect( pdx_thismilieu , ( in ) );
return( pdx_tmp_2460 );
}
	public java.lang.Object pdxm_getMyEll( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_3900 = ( this ).pdx_ObjectMemberAccess_pdx_getmyEll( pdx_thismilieu );
return( pdx_tmp_3900 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setMyLine( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_5820 = ( this ).pdx_ObjectMemberAccess_pdx_asgmyLine( pdx_thismilieu , ( in ) );
return( pdx_tmp_5820 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setMyRct( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_5260 = ( this ).pdx_ObjectMemberAccess_pdx_asgmyRct( pdx_thismilieu , ( in ) );
return( pdx_tmp_5260 );
}
	public java.lang.Object pdxm_getMyStroke( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_3340 = ( this ).pdx_ObjectMemberAccess_pdx_getmyStroke( pdx_thismilieu );
return( pdx_tmp_3340 );
}
	public double pdxm_getBasicStrokeWidth( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final double pdx_tmp_2780 = ( this ).pdx_ObjectMemberAccess_pdx_getbasicStrokeWidth( pdx_thismilieu );
return( pdx_tmp_2780 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setBasicStrokeWidth( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final double  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_3020 = ( this ).pdx_ObjectMemberAccess_pdx_asgbasicStrokeWidth( pdx_thismilieu , ( in ) );
return( pdx_tmp_3020 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setLineColor( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_1340 = ( this ).pdx_ObjectMemberAccess_pdx_asglineColor( pdx_thismilieu , ( in ) );
return( pdx_tmp_1340 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setMyRound( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_4700 = ( this ).pdx_ObjectMemberAccess_pdx_asgmyRound( pdx_thismilieu , ( in ) );
return( pdx_tmp_4700 );
}
	public java.lang.Object pdxm_getMyRct( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_5020 = ( this ).pdx_ObjectMemberAccess_pdx_getmyRct( pdx_thismilieu );
return( pdx_tmp_5020 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setRenderingMode( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final int  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_780 = ( this ).pdx_ObjectMemberAccess_pdx_asgrenderingMode( pdx_thismilieu , ( in ) );
return( pdx_tmp_780 );
}
	}

