
/**************
* This source file was generated by JUndo compiler version 070726A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See http://sourceforge.net/projects/jundo
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.  See the associated .JUndo file for license and
* copyright information.
* This File Generated : Sat Aug 11 07:21:28 MDT 2007
* From Input File : DrawingPolygonalObjectBase.JUndo
**************/

package verdantium.standard;

public abstract class pdx_DrawingPolygonalObjectBase_pdx_ObjectRef extends verdantium.standard.pdx_DrawingObject_pdx_ObjectRef
	{
protected pdx_DrawingPolygonalObjectBase_pdx_ObjectRef( jundo.runtime.KeyRef Key )
{
super( Key );
}

	public static verdantium.standard.pdx_DrawingPolygonalObjectBase_pdx_PairRef pdx_zero( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final verdantium.standard.pdx_DrawingPolygonalObjectBase_pdx_ObjectRef in )
{
final verdantium.standard.pdx_DrawingPolygonalObjectBase_pdx_PairRef tx = new verdantium.standard.pdx_DrawingPolygonalObjectBase_pdx_PairRef( in , pdx_thismilieu );
final jundo.runtime.ExtMilieuRef t0 = tx.getMilieu();
final jundo.runtime.ExtMilieuRef t1 = jundo.runtime.Runtime.asgDoubleObjectMember( tx.getObject() , "basicStrokeWidth" , t0 , 0 );
final jundo.runtime.ExtMilieuRef t2 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "prevBez" , t1 , null );
final jundo.runtime.ExtMilieuRef t3 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "prevInt" , t2 , null );
final jundo.runtime.ExtMilieuRef t4 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "myStroke" , t3 , null );
final jundo.runtime.ExtMilieuRef t5 = jundo.runtime.Runtime.asgIntObjectMember( tx.getObject() , "renderingMode" , t4 , 0 );
final jundo.runtime.ExtMilieuRef t6 = jundo.runtime.Runtime.asgBooleanObjectMember( tx.getObject() , "curveRender" , t5 , false );
final jundo.runtime.ExtMilieuRef t7 = jundo.runtime.Runtime.asgBooleanObjectMember( tx.getObject() , "chordP" , t6 , false );
final jundo.runtime.ExtMilieuRef t8 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "lineColor" , t7 , null );
final jundo.runtime.ExtMilieuRef t9 = jundo.runtime.Runtime.asgIntObjectMember( tx.getObject() , "bezMode" , t8 , 0 );
final jundo.runtime.ExtMilieuRef t10 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "fillColor" , t9 , null );
final jundo.runtime.ExtMilieuRef t11 = jundo.runtime.Runtime.asgBooleanObjectMember( tx.getObject() , "filledRender" , t10 , false );
final jundo.runtime.ExtMilieuRef t12 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "myPath" , t11 , null );
final verdantium.standard.pdx_DrawingPolygonalObjectBase_pdx_PairRef z = new verdantium.standard.pdx_DrawingPolygonalObjectBase_pdx_PairRef( in , t12 );
return( z );
}
	public static void pdx_initClassMembers( )
{
}

	static
{
pdx_initClassMembers();
}

	public double pdx_ObjectMemberAccess_pdx_getbasicStrokeWidth( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getDoubleObjectMember( this , "basicStrokeWidth" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgbasicStrokeWidth( final jundo.runtime.ExtMilieuRef mil , final double val )
{
return( jundo.runtime.Runtime.asgDoubleObjectMember( this , "basicStrokeWidth" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getprevBez( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "prevBez" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgprevBez( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "prevBez" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getprevInt( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "prevInt" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgprevInt( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "prevInt" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getmyStroke( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "myStroke" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgmyStroke( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "myStroke" , mil , val ) );
}
	public int pdx_ObjectMemberAccess_pdx_getrenderingMode( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getIntObjectMember( this , "renderingMode" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgrenderingMode( final jundo.runtime.ExtMilieuRef mil , final int val )
{
return( jundo.runtime.Runtime.asgIntObjectMember( this , "renderingMode" , mil , val ) );
}
	public boolean pdx_ObjectMemberAccess_pdx_getcurveRender( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getBooleanObjectMember( this , "curveRender" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgcurveRender( final jundo.runtime.ExtMilieuRef mil , final boolean val )
{
return( jundo.runtime.Runtime.asgBooleanObjectMember( this , "curveRender" , mil , val ) );
}
	public boolean pdx_ObjectMemberAccess_pdx_getchordP( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getBooleanObjectMember( this , "chordP" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgchordP( final jundo.runtime.ExtMilieuRef mil , final boolean val )
{
return( jundo.runtime.Runtime.asgBooleanObjectMember( this , "chordP" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getlineColor( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "lineColor" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asglineColor( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "lineColor" , mil , val ) );
}
	public int pdx_ObjectMemberAccess_pdx_getbezMode( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getIntObjectMember( this , "bezMode" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgbezMode( final jundo.runtime.ExtMilieuRef mil , final int val )
{
return( jundo.runtime.Runtime.asgIntObjectMember( this , "bezMode" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getfillColor( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "fillColor" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgfillColor( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "fillColor" , mil , val ) );
}
	public boolean pdx_ObjectMemberAccess_pdx_getfilledRender( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getBooleanObjectMember( this , "filledRender" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgfilledRender( final jundo.runtime.ExtMilieuRef mil , final boolean val )
{
return( jundo.runtime.Runtime.asgBooleanObjectMember( this , "filledRender" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getmyPath( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "myPath" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgmyPath( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "myPath" , mil , val ) );
}
	public jundo.runtime.ExtMilieuRef pdxm_setBezMode( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final int  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_5820 = ( this ).pdx_ObjectMemberAccess_pdx_asgbezMode( pdx_thismilieu , ( in ) );
return( pdx_tmp_5820 );
}
	public boolean pdxm_getFilledRender( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final boolean pdx_tmp_540 = ( this ).pdx_ObjectMemberAccess_pdx_getfilledRender( pdx_thismilieu );
return( pdx_tmp_540 );
}
	public java.lang.Object pdxm_getMyPath( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_1660 = ( this ).pdx_ObjectMemberAccess_pdx_getmyPath( pdx_thismilieu );
return( pdx_tmp_1660 );
}
	public java.lang.Object pdxm_getPrevBez( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_5020 = ( this ).pdx_ObjectMemberAccess_pdx_getprevBez( pdx_thismilieu );
return( pdx_tmp_5020 );
}
	public java.lang.Object pdxm_getPrevInt( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_4460 = ( this ).pdx_ObjectMemberAccess_pdx_getprevInt( pdx_thismilieu );
return( pdx_tmp_4460 );
}
	public java.lang.Object pdxm_getFillColor( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_2780 = ( this ).pdx_ObjectMemberAccess_pdx_getfillColor( pdx_thismilieu );
return( pdx_tmp_2780 );
}
	public int pdxm_getRenderingMode( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final int pdx_tmp_6700 = ( this ).pdx_ObjectMemberAccess_pdx_getrenderingMode( pdx_thismilieu );
return( pdx_tmp_6700 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setFillColor( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_3020 = ( this ).pdx_ObjectMemberAccess_pdx_asgfillColor( pdx_thismilieu , ( in ) );
return( pdx_tmp_3020 );
}
	public java.lang.Object pdxm_getLineColor( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_2220 = ( this ).pdx_ObjectMemberAccess_pdx_getlineColor( pdx_thismilieu );
return( pdx_tmp_2220 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setMyStroke( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_4140 = ( this ).pdx_ObjectMemberAccess_pdx_asgmyStroke( pdx_thismilieu , ( in ) );
return( pdx_tmp_4140 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setMyPath( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_1900 = ( this ).pdx_ObjectMemberAccess_pdx_asgmyPath( pdx_thismilieu , ( in ) );
return( pdx_tmp_1900 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setPrevBez( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_5260 = ( this ).pdx_ObjectMemberAccess_pdx_asgprevBez( pdx_thismilieu , ( in ) );
return( pdx_tmp_5260 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setFilledRender( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final boolean  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_780 = ( this ).pdx_ObjectMemberAccess_pdx_asgfilledRender( pdx_thismilieu , ( in ) );
return( pdx_tmp_780 );
}
	public double pdxm_getBasicStrokeWidth( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final double pdx_tmp_3340 = ( this ).pdx_ObjectMemberAccess_pdx_getbasicStrokeWidth( pdx_thismilieu );
return( pdx_tmp_3340 );
}
	public java.lang.Object pdxm_getMyStroke( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_3900 = ( this ).pdx_ObjectMemberAccess_pdx_getmyStroke( pdx_thismilieu );
return( pdx_tmp_3900 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setPrevInt( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_4700 = ( this ).pdx_ObjectMemberAccess_pdx_asgprevInt( pdx_thismilieu , ( in ) );
return( pdx_tmp_4700 );
}
	public boolean pdxm_getCurveRender( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final boolean pdx_tmp_1100 = ( this ).pdx_ObjectMemberAccess_pdx_getcurveRender( pdx_thismilieu );
return( pdx_tmp_1100 );
}
	public boolean pdxm_getChordP( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final boolean pdx_tmp_6140 = ( this ).pdx_ObjectMemberAccess_pdx_getchordP( pdx_thismilieu );
return( pdx_tmp_6140 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setBasicStrokeWidth( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final double  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_3580 = ( this ).pdx_ObjectMemberAccess_pdx_asgbasicStrokeWidth( pdx_thismilieu , ( in ) );
return( pdx_tmp_3580 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setLineColor( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_2460 = ( this ).pdx_ObjectMemberAccess_pdx_asglineColor( pdx_thismilieu , ( in ) );
return( pdx_tmp_2460 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setChordP( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final boolean  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_6380 = ( this ).pdx_ObjectMemberAccess_pdx_asgchordP( pdx_thismilieu , ( in ) );
return( pdx_tmp_6380 );
}
	public int pdxm_getBezMode( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final int pdx_tmp_5580 = ( this ).pdx_ObjectMemberAccess_pdx_getbezMode( pdx_thismilieu );
return( pdx_tmp_5580 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setCurveRender( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final boolean  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_1340 = ( this ).pdx_ObjectMemberAccess_pdx_asgcurveRender( pdx_thismilieu , ( in ) );
return( pdx_tmp_1340 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setRenderingMode( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final int  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_6940 = ( this ).pdx_ObjectMemberAccess_pdx_asgrenderingMode( pdx_thismilieu , ( in ) );
return( pdx_tmp_6940 );
}
	}

