
/**************
* This source file was generated by JUndo compiler version 070726A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See http://sourceforge.net/projects/jundo
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.  See the associated .JUndo file for license and
* copyright information.
* This File Generated : Wed Aug 01 16:39:11 MDT 2007
* From Input File : DrawAppModel.JUndo
**************/

package verdantium.standard;

class pdx_DrawAppModel_pdx_PairRef extends jundo.runtime.ExtPair
	{
public pdx_DrawAppModel_pdx_PairRef( pdx_DrawAppModel_pdx_ObjectRef obj , jundo.runtime.ExtMilieuRef mil )
{
super( obj , mil );
}
	}

