
/**************
* This source file was generated by JUndo compiler version 070726A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See http://sourceforge.net/projects/jundo
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.  See the associated .JUndo file for license and
* copyright information.
* This File Generated : Sat Aug 11 07:21:30 MDT 2007
* From Input File : DrawingPolygonalObjectBase.JUndo
**************/

package verdantium.standard;

public class pdx_DrawingPolygonalObjectBase_pdx_PairRef extends verdantium.standard.pdx_DrawingObject_pdx_PairRef
	{
public pdx_DrawingPolygonalObjectBase_pdx_PairRef( pdx_DrawingPolygonalObjectBase_pdx_ObjectRef obj , jundo.runtime.ExtMilieuRef mil )
{
super( obj , mil );
}
	}

