
/**************
* This source file was generated by JUndo compiler version 070726A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See http://sourceforge.net/projects/jundo
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.  See the associated .JUndo file for license and
* copyright information.
* This File Generated : Sat Aug 04 10:53:56 MDT 2007
* From Input File : DrawingObject.JUndo
**************/

package verdantium.standard;

public abstract class pdx_DrawingObject_pdx_ObjectRef extends umeta.pdx_Meta_pdx_ObjectRef implements umeta.pdx_Versionable_pdx_ObjectRef
	{
protected pdx_DrawingObject_pdx_ObjectRef( jundo.runtime.KeyRef Key )
{
super( Key );
}

	public static verdantium.standard.pdx_DrawingObject_pdx_PairRef pdx_zero( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final verdantium.standard.pdx_DrawingObject_pdx_ObjectRef in )
{
final verdantium.standard.pdx_DrawingObject_pdx_PairRef tx = new verdantium.standard.pdx_DrawingObject_pdx_PairRef( in , pdx_thismilieu );
final jundo.runtime.ExtMilieuRef t0 = tx.getMilieu();
final verdantium.standard.pdx_DrawingObject_pdx_PairRef z = new verdantium.standard.pdx_DrawingObject_pdx_PairRef( in , t0 );
return( z );
}
	public static void pdx_initClassMembers( )
{
}

	static
{
pdx_initClassMembers();
}

	abstract public java.lang.Object pdxm_downBuild( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
;
	public java.lang.Object pdxm_clickedInRegion( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  thePort , final int  toolMode , final java.lang.Object  inPoint )
{
return( ( null ) );
}
	abstract public jundo.runtime.ExtMilieuRef pdxm_draw( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  thePort , final java.lang.Object  g , final int  toolMode )
;
	abstract public jundo.runtime.ExtMilieuRef pdxm_drawTools( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  thePort , final java.lang.Object  g , final int  toolMode )
;
	}

