
/**************
* This source file was generated by JUndo compiler version 051002A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See http://sourceforge.net/projects/jundo
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.  See the associated .JUndo file for license and
* copyright information.
* This File Generated : Fri Oct 28 21:42:54 MDT 2005
* From Input File : BackgroundModel.JUndo
**************/

package verdantium.xapp;

class pdx_BackgroundModel_pdx_PairRef extends jundo.runtime.ExtPair
	{
public pdx_BackgroundModel_pdx_PairRef( pdx_BackgroundModel_pdx_ObjectRef obj , jundo.runtime.ExtMilieuRef mil )
{
super( obj , mil );
}
	}

