
/**************
* This source file was generated by JUndo compiler version 051002A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See http://sourceforge.net/projects/jundo
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.  See the associated .JUndo file for license and
* copyright information.
* This File Generated : Fri Oct 28 21:43:30 MDT 2005
* From Input File : BorderModel.JUndo
**************/

package verdantium.xapp;

class pdx_BorderModel_pdx_ObjectRef extends jundo.runtime.ExtObjectRef
	{
protected pdx_BorderModel_pdx_ObjectRef( jundo.runtime.KeyRef Key )
{
super( Key );
}

public static verdantium.xapp.pdx_BorderModel_pdx_PairRef createOID_BorderModel( jundo.runtime.ExtMilieuRef InMil )
{
jundo.runtime.ExtMilieuRef NewMil = jundo.runtime.Runtime.createOIDmilieu( InMil );
int NewID = NewMil.getMaxID();
jundo.runtime.KeyRef MyKey = jundo.runtime.Runtime.getKeyRef( NewID );
pdx_BorderModel_pdx_ObjectRef NewObj = 
	new pdx_BorderModel_pdx_ObjectRef( MyKey );
verdantium.xapp.pdx_BorderModel_pdx_PairRef ret = new verdantium.xapp.pdx_BorderModel_pdx_PairRef( NewObj , NewMil );
return( ret );
}
	public static verdantium.xapp.pdx_BorderModel_pdx_PairRef pdxm_new_BorderModel( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  borderClass , final java.lang.Object  borderTypes , final java.lang.Object  borderParam )
{
final verdantium.xapp.pdx_BorderModel_pdx_PairRef pdx_tmp_2482 = verdantium.xapp.pdx_BorderModel_pdx_ObjectRef.pdxm_allocate_BorderModel( ( pdx_thismilieu ) );
final verdantium.xapp.pdx_BorderModel_pdx_ObjectRef pdx_tmp_2480 = (verdantium.xapp.pdx_BorderModel_pdx_ObjectRef)( pdx_tmp_2482.getObject() );
final jundo.runtime.ExtMilieuRef pdx_tmp_2481 = pdx_tmp_2482.getMilieu();
final jundo.runtime.ExtMilieuRef pdx_tmp_2880 = pdx_tmp_2480.pdxm_setBorderObject( pdx_tmp_2481 , ( borderClass ) , ( borderTypes ) , ( borderParam ) );
return( new verdantium.xapp.pdx_BorderModel_pdx_PairRef( pdx_tmp_2480 , ( pdx_tmp_2880 ) ) );
}
	public static verdantium.xapp.pdx_BorderModel_pdx_PairRef pdxm_allocate_BorderModel( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.xapp.pdx_BorderModel_pdx_PairRef t1 = pdx_BorderModel_pdx_ObjectRef.createOID_BorderModel( pdx_thismilieu );
final verdantium.xapp.pdx_BorderModel_pdx_PairRef t2 = pdx_zero( t1.getMilieu() , (verdantium.xapp.pdx_BorderModel_pdx_ObjectRef)( t1.getObject() ) );

return( t2 );
}
	public static verdantium.xapp.pdx_BorderModel_pdx_PairRef pdx_zero( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final verdantium.xapp.pdx_BorderModel_pdx_ObjectRef in )
{
final verdantium.xapp.pdx_BorderModel_pdx_PairRef tx = new verdantium.xapp.pdx_BorderModel_pdx_PairRef( in , pdx_thismilieu );
final jundo.runtime.ExtMilieuRef t0 = tx.getMilieu();
final jundo.runtime.ExtMilieuRef t1 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "borderClass" , t0 , null );
final jundo.runtime.ExtMilieuRef t2 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "borderTypes" , t1 , null );
final jundo.runtime.ExtMilieuRef t3 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "borderParam" , t2 , null );
final verdantium.xapp.pdx_BorderModel_pdx_PairRef z = new verdantium.xapp.pdx_BorderModel_pdx_PairRef( in , t3 );
return( z );
}
	public static void pdx_initClassMembers( )
{
}

	static
{
pdx_initClassMembers();
}

	public java.lang.Object pdx_ObjectMemberAccess_pdx_getborderClass( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "borderClass" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgborderClass( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "borderClass" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getborderTypes( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "borderTypes" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgborderTypes( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "borderTypes" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getborderParam( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "borderParam" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgborderParam( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "borderParam" , mil , val ) );
}
	public java.lang.Object pdxm_getBorderParam( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_880 = ( this ).pdx_ObjectMemberAccess_pdx_getborderParam( pdx_thismilieu );
return( pdx_tmp_880 );
}
	public java.lang.Object pdxm_getBorderTypes( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_700 = ( this ).pdx_ObjectMemberAccess_pdx_getborderTypes( pdx_thismilieu );
return( pdx_tmp_700 );
}
	public java.lang.Object pdxm_getBorderClass( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_520 = ( this ).pdx_ObjectMemberAccess_pdx_getborderClass( pdx_thismilieu );
return( pdx_tmp_520 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setBorderObject( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  borderClass , final java.lang.Object  borderTypes , final java.lang.Object  borderParam )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_1320 = ( this ).pdx_ObjectMemberAccess_pdx_asgborderClass( ( pdx_thismilieu ) , ( borderClass ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_1440 = ( this ).pdx_ObjectMemberAccess_pdx_asgborderTypes( pdx_tmp_1320 , ( borderTypes ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_1560 = ( this ).pdx_ObjectMemberAccess_pdx_asgborderParam( pdx_tmp_1440 , ( borderParam ) );
return( ( pdx_tmp_1560 ) );
}
	}

