
/**************
* This source file was generated by JUndo compiler version 051002A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See http://sourceforge.net/projects/jundo
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.  See the associated .JUndo file for license and
* copyright information.
* This File Generated : Fri Oct 28 21:42:53 MDT 2005
* From Input File : BackgroundModel.JUndo
**************/

package verdantium.xapp;

class pdx_BackgroundModel_pdx_ObjectRef extends jundo.runtime.ExtObjectRef
	{
protected pdx_BackgroundModel_pdx_ObjectRef( jundo.runtime.KeyRef Key )
{
super( Key );
}

public static verdantium.xapp.pdx_BackgroundModel_pdx_PairRef createOID_BackgroundModel( jundo.runtime.ExtMilieuRef InMil )
{
jundo.runtime.ExtMilieuRef NewMil = jundo.runtime.Runtime.createOIDmilieu( InMil );
int NewID = NewMil.getMaxID();
jundo.runtime.KeyRef MyKey = jundo.runtime.Runtime.getKeyRef( NewID );
pdx_BackgroundModel_pdx_ObjectRef NewObj = 
	new pdx_BackgroundModel_pdx_ObjectRef( MyKey );
verdantium.xapp.pdx_BackgroundModel_pdx_PairRef ret = new verdantium.xapp.pdx_BackgroundModel_pdx_PairRef( NewObj , NewMil );
return( ret );
}
	public static verdantium.xapp.pdx_BackgroundModel_pdx_PairRef pdxm_new_BackgroundModel( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  backgroundColor , final boolean  opaqueFlag )
{
final verdantium.xapp.pdx_BackgroundModel_pdx_PairRef pdx_tmp_1982 = verdantium.xapp.pdx_BackgroundModel_pdx_ObjectRef.pdxm_allocate_BackgroundModel( ( pdx_thismilieu ) );
final verdantium.xapp.pdx_BackgroundModel_pdx_ObjectRef pdx_tmp_1980 = (verdantium.xapp.pdx_BackgroundModel_pdx_ObjectRef)( pdx_tmp_1982.getObject() );
final jundo.runtime.ExtMilieuRef pdx_tmp_1981 = pdx_tmp_1982.getMilieu();
final jundo.runtime.ExtMilieuRef pdx_tmp_2340 = pdx_tmp_1980.pdxm_setBackgroundState( pdx_tmp_1981 , ( backgroundColor ) , ( opaqueFlag ) );
return( new verdantium.xapp.pdx_BackgroundModel_pdx_PairRef( pdx_tmp_1980 , ( pdx_tmp_2340 ) ) );
}
	public static verdantium.xapp.pdx_BackgroundModel_pdx_PairRef pdxm_allocate_BackgroundModel( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.xapp.pdx_BackgroundModel_pdx_PairRef t1 = pdx_BackgroundModel_pdx_ObjectRef.createOID_BackgroundModel( pdx_thismilieu );
final verdantium.xapp.pdx_BackgroundModel_pdx_PairRef t2 = pdx_zero( t1.getMilieu() , (verdantium.xapp.pdx_BackgroundModel_pdx_ObjectRef)( t1.getObject() ) );

return( t2 );
}
	public static verdantium.xapp.pdx_BackgroundModel_pdx_PairRef pdx_zero( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final verdantium.xapp.pdx_BackgroundModel_pdx_ObjectRef in )
{
final verdantium.xapp.pdx_BackgroundModel_pdx_PairRef tx = new verdantium.xapp.pdx_BackgroundModel_pdx_PairRef( in , pdx_thismilieu );
final jundo.runtime.ExtMilieuRef t0 = tx.getMilieu();
final jundo.runtime.ExtMilieuRef t1 = jundo.runtime.Runtime.asgBooleanObjectMember( tx.getObject() , "opaqueFlag" , t0 , false );
final jundo.runtime.ExtMilieuRef t2 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "backgroundColor" , t1 , null );
final verdantium.xapp.pdx_BackgroundModel_pdx_PairRef z = new verdantium.xapp.pdx_BackgroundModel_pdx_PairRef( in , t2 );
return( z );
}
	public static void pdx_initClassMembers( )
{
}

	static
{
pdx_initClassMembers();
}

	public boolean pdx_ObjectMemberAccess_pdx_getopaqueFlag( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getBooleanObjectMember( this , "opaqueFlag" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgopaqueFlag( final jundo.runtime.ExtMilieuRef mil , final boolean val )
{
return( jundo.runtime.Runtime.asgBooleanObjectMember( this , "opaqueFlag" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getbackgroundColor( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "backgroundColor" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgbackgroundColor( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "backgroundColor" , mil , val ) );
}
	public boolean pdxm_isOpaqueFlag( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final boolean pdx_tmp_620 = ( this ).pdx_ObjectMemberAccess_pdx_getopaqueFlag( pdx_thismilieu );
return( pdx_tmp_620 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setBackgroundState( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  backgroundColor , final boolean  opaqueFlag )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_1000 = ( this ).pdx_ObjectMemberAccess_pdx_asgbackgroundColor( ( pdx_thismilieu ) , ( backgroundColor ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_1120 = ( this ).pdx_ObjectMemberAccess_pdx_asgopaqueFlag( pdx_tmp_1000 , ( opaqueFlag ) );
return( ( pdx_tmp_1120 ) );
}
	public java.lang.Object pdxm_getBackgroundColor( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_440 = ( this ).pdx_ObjectMemberAccess_pdx_getbackgroundColor( pdx_thismilieu );
return( pdx_tmp_440 );
}
	}

