
/**************
* This source file was generated by JUndo compiler version 050827A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See [put web site address here]
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.
* This File Generated : Thu Sep 01 21:58:33 MDT 2005
* From Input File : ShowLightsModel.JUndo
**************/

package verdantium.standard.showlights;

class pdx_ShowLightsModel_pdx_ObjectRef extends jundo.runtime.ExtObjectRef
	{
protected pdx_ShowLightsModel_pdx_ObjectRef(  jundo.runtime.KeyRef Key )
{
super( Key );
}

public static verdantium.standard.showlights.pdx_ShowLightsModel_pdx_PairRef createOID_ShowLightsModel( jundo.runtime.ExtMilieuRef InMil )
{
jundo.runtime.ExtMilieuRef NewMil = jundo.runtime.Runtime.createOIDmilieu( InMil );
int NewID = NewMil.getMaxID();
jundo.runtime.KeyRef MyKey = jundo.runtime.Runtime.getKeyRef( NewID );
pdx_ShowLightsModel_pdx_ObjectRef NewObj = 
	new pdx_ShowLightsModel_pdx_ObjectRef( MyKey );
verdantium.standard.showlights.pdx_ShowLightsModel_pdx_PairRef ret = new verdantium.standard.showlights.pdx_ShowLightsModel_pdx_PairRef( NewObj , NewMil );
return( ret );
}
	public static verdantium.standard.showlights.pdx_ShowLightsModel_pdx_PairRef pdxm_new_ShowLightsModel( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final boolean  onlyDesignerEdits , final int  swatchSize , final int  swatchInset , final int  tbl_delay , final int  num_frames , final java.lang.Object  endColor , final java.lang.Object  startColor )
{
final verdantium.standard.showlights.pdx_ShowLightsModel_pdx_PairRef pdx_tmp_5042 = verdantium.standard.showlights.pdx_ShowLightsModel_pdx_ObjectRef.pdxm_allocate_ShowLightsModel( ( pdx_thismilieu ) );
final verdantium.standard.showlights.pdx_ShowLightsModel_pdx_ObjectRef pdx_tmp_5040 = (verdantium.standard.showlights.pdx_ShowLightsModel_pdx_ObjectRef)( pdx_tmp_5042.getObject() );
final jundo.runtime.ExtMilieuRef pdx_tmp_5041 = pdx_tmp_5042.getMilieu();
final jundo.runtime.ExtMilieuRef pdx_tmp_5360 = pdx_tmp_5040.pdxm_setOnlyDesignerEdits( pdx_tmp_5041 , ( onlyDesignerEdits ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_5520 = pdx_tmp_5040.pdxm_setResolution( pdx_tmp_5360 , ( swatchSize ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_5680 = pdx_tmp_5040.pdxm_setInset( pdx_tmp_5520 , ( swatchInset ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_5840 = pdx_tmp_5040.pdxm_setDelay( pdx_tmp_5680 , ( tbl_delay ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_6000 = pdx_tmp_5040.pdxm_setNumFrames( pdx_tmp_5840 , ( num_frames ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_6160 = pdx_tmp_5040.pdxm_setEndColor( pdx_tmp_6000 , ( endColor ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_6320 = pdx_tmp_5040.pdxm_setStartColor( pdx_tmp_6160 , ( startColor ) );
return( new verdantium.standard.showlights.pdx_ShowLightsModel_pdx_PairRef( pdx_tmp_5040 , ( pdx_tmp_6320 ) ) );
}
	public static verdantium.standard.showlights.pdx_ShowLightsModel_pdx_PairRef pdxm_allocate_ShowLightsModel( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.standard.showlights.pdx_ShowLightsModel_pdx_PairRef t1 = pdx_ShowLightsModel_pdx_ObjectRef.createOID_ShowLightsModel( pdx_thismilieu );
final verdantium.standard.showlights.pdx_ShowLightsModel_pdx_PairRef t2 = pdx_zero( t1.getMilieu() , (verdantium.standard.showlights.pdx_ShowLightsModel_pdx_ObjectRef)( t1.getObject() ) );

return( t2 );
}
	public static verdantium.standard.showlights.pdx_ShowLightsModel_pdx_PairRef pdx_zero( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final verdantium.standard.showlights.pdx_ShowLightsModel_pdx_ObjectRef in )
{
final verdantium.standard.showlights.pdx_ShowLightsModel_pdx_PairRef tx = new verdantium.standard.showlights.pdx_ShowLightsModel_pdx_PairRef( in , pdx_thismilieu );
final jundo.runtime.ExtMilieuRef t0 = tx.getMilieu();
final jundo.runtime.ExtMilieuRef t1 = jundo.runtime.Runtime.asgIntObjectMember( tx.getObject() , "swatchSize" , t0 , 0 );
final jundo.runtime.ExtMilieuRef t2 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "endColor" , t1 , null );
final jundo.runtime.ExtMilieuRef t3 = jundo.runtime.Runtime.asgIntObjectMember( tx.getObject() , "swatchInset" , t2 , 0 );
final jundo.runtime.ExtMilieuRef t4 = jundo.runtime.Runtime.asgIntObjectMember( tx.getObject() , "tbl_delay" , t3 , 0 );
final jundo.runtime.ExtMilieuRef t5 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "startColor" , t4 , null );
final jundo.runtime.ExtMilieuRef t6 = jundo.runtime.Runtime.asgIntObjectMember( tx.getObject() , "num_frames" , t5 , 0 );
final jundo.runtime.ExtMilieuRef t7 = jundo.runtime.Runtime.asgBooleanObjectMember( tx.getObject() , "onlyDesignerEdits" , t6 , false );
final verdantium.standard.showlights.pdx_ShowLightsModel_pdx_PairRef z = new verdantium.standard.showlights.pdx_ShowLightsModel_pdx_PairRef( in , t7 );
return( z );
}
	public static void pdx_initClassMembers( )
{
}

	static
{
pdx_initClassMembers();
}

	public int pdx_ObjectMemberAccess_pdx_getswatchSize( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getIntObjectMember( this , "swatchSize" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgswatchSize( final jundo.runtime.ExtMilieuRef mil , final int val )
{
return( jundo.runtime.Runtime.asgIntObjectMember( this , "swatchSize" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getendColor( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "endColor" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgendColor( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "endColor" , mil , val ) );
}
	public int pdx_ObjectMemberAccess_pdx_getswatchInset( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getIntObjectMember( this , "swatchInset" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgswatchInset( final jundo.runtime.ExtMilieuRef mil , final int val )
{
return( jundo.runtime.Runtime.asgIntObjectMember( this , "swatchInset" , mil , val ) );
}
	public int pdx_ObjectMemberAccess_pdx_gettbl_delay( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getIntObjectMember( this , "tbl_delay" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgtbl_delay( final jundo.runtime.ExtMilieuRef mil , final int val )
{
return( jundo.runtime.Runtime.asgIntObjectMember( this , "tbl_delay" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getstartColor( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "startColor" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgstartColor( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "startColor" , mil , val ) );
}
	public int pdx_ObjectMemberAccess_pdx_getnum_frames( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getIntObjectMember( this , "num_frames" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgnum_frames( final jundo.runtime.ExtMilieuRef mil , final int val )
{
return( jundo.runtime.Runtime.asgIntObjectMember( this , "num_frames" , mil , val ) );
}
	public boolean pdx_ObjectMemberAccess_pdx_getonlyDesignerEdits( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getBooleanObjectMember( this , "onlyDesignerEdits" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgonlyDesignerEdits( final jundo.runtime.ExtMilieuRef mil , final boolean val )
{
return( jundo.runtime.Runtime.asgBooleanObjectMember( this , "onlyDesignerEdits" , mil , val ) );
}
	public jundo.runtime.ExtMilieuRef pdxm_setDelay( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final int  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_2560 = ( this ).pdx_ObjectMemberAccess_pdx_asgtbl_delay( pdx_thismilieu , ( in ) );
return( pdx_tmp_2560 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setStartColor( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_4000 = ( this ).pdx_ObjectMemberAccess_pdx_asgstartColor( pdx_thismilieu , ( in ) );
return( pdx_tmp_4000 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setInset( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final int  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_2080 = ( this ).pdx_ObjectMemberAccess_pdx_asgswatchInset( pdx_thismilieu , ( in ) );
return( pdx_tmp_2080 );
}
	public java.lang.Object pdxm_getEndColor( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_3280 = ( this ).pdx_ObjectMemberAccess_pdx_getendColor( pdx_thismilieu );
return( pdx_tmp_3280 );
}
	public int pdxm_getDelay( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final int pdx_tmp_2320 = ( this ).pdx_ObjectMemberAccess_pdx_gettbl_delay( pdx_thismilieu );
return( pdx_tmp_2320 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setResolution( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final int  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_1600 = ( this ).pdx_ObjectMemberAccess_pdx_asgswatchSize( pdx_thismilieu , ( in ) );
return( pdx_tmp_1600 );
}
	public int pdxm_getInset( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final int pdx_tmp_1840 = ( this ).pdx_ObjectMemberAccess_pdx_getswatchInset( pdx_thismilieu );
return( pdx_tmp_1840 );
}
	public java.lang.Object pdxm_getStartColor( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_3760 = ( this ).pdx_ObjectMemberAccess_pdx_getstartColor( pdx_thismilieu );
return( pdx_tmp_3760 );
}
	public boolean pdxm_isOnlyDesignerEdits( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final boolean pdx_tmp_880 = ( this ).pdx_ObjectMemberAccess_pdx_getonlyDesignerEdits( pdx_thismilieu );
return( pdx_tmp_880 );
}
	public int pdxm_getResolution( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final int pdx_tmp_1360 = ( this ).pdx_ObjectMemberAccess_pdx_getswatchSize( pdx_thismilieu );
return( pdx_tmp_1360 );
}
	public int pdxm_getNumFrames( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final int pdx_tmp_2800 = ( this ).pdx_ObjectMemberAccess_pdx_getnum_frames( pdx_thismilieu );
return( pdx_tmp_2800 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setOnlyDesignerEdits( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final boolean  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_1120 = ( this ).pdx_ObjectMemberAccess_pdx_asgonlyDesignerEdits( pdx_thismilieu , ( in ) );
return( pdx_tmp_1120 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setEndColor( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_3520 = ( this ).pdx_ObjectMemberAccess_pdx_asgendColor( pdx_thismilieu , ( in ) );
return( pdx_tmp_3520 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setNumFrames( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final int  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_3040 = ( this ).pdx_ObjectMemberAccess_pdx_asgnum_frames( pdx_thismilieu , ( in ) );
return( pdx_tmp_3040 );
}
	}

