
/**************
* This source file was generated by JUndo compiler version 051002A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See http://sourceforge.net/projects/jundo
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.  See the associated .JUndo file for license and
* copyright information.
* This File Generated : Fri Oct 28 21:36:42 MDT 2005
* From Input File : HyperButtonModel.JUndo
**************/

package verdantium.standard.data;

public class pdx_HyperButtonModel_pdx_ObjectRef extends jundo.runtime.ExtObjectRef
	{
protected pdx_HyperButtonModel_pdx_ObjectRef( jundo.runtime.KeyRef Key )
{
super( Key );
}

public static verdantium.standard.data.pdx_HyperButtonModel_pdx_PairRef createOID_HyperButtonModel( jundo.runtime.ExtMilieuRef InMil )
{
jundo.runtime.ExtMilieuRef NewMil = jundo.runtime.Runtime.createOIDmilieu( InMil );
int NewID = NewMil.getMaxID();
jundo.runtime.KeyRef MyKey = jundo.runtime.Runtime.getKeyRef( NewID );
pdx_HyperButtonModel_pdx_ObjectRef NewObj = 
	new pdx_HyperButtonModel_pdx_ObjectRef( MyKey );
verdantium.standard.data.pdx_HyperButtonModel_pdx_PairRef ret = new verdantium.standard.data.pdx_HyperButtonModel_pdx_PairRef( NewObj , NewMil );
return( ret );
}
	public static verdantium.standard.data.pdx_HyperButtonModel_pdx_PairRef pdxm_new_HyperButtonModel( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.standard.data.pdx_HyperButtonModel_pdx_PairRef pdx_tmp_4662 = verdantium.standard.data.pdx_HyperButtonModel_pdx_ObjectRef.pdxm_allocate_HyperButtonModel( ( pdx_thismilieu ) );
final verdantium.standard.data.pdx_HyperButtonModel_pdx_ObjectRef pdx_tmp_4660 = (verdantium.standard.data.pdx_HyperButtonModel_pdx_ObjectRef)( pdx_tmp_4662.getObject() );
final jundo.runtime.ExtMilieuRef pdx_tmp_4661 = pdx_tmp_4662.getMilieu();
return( new verdantium.standard.data.pdx_HyperButtonModel_pdx_PairRef( pdx_tmp_4660 , ( pdx_tmp_4661 ) ) );
}
	public static verdantium.standard.data.pdx_HyperButtonModel_pdx_PairRef pdxm_allocate_HyperButtonModel( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final verdantium.standard.data.pdx_HyperButtonModel_pdx_PairRef t1 = pdx_HyperButtonModel_pdx_ObjectRef.createOID_HyperButtonModel( pdx_thismilieu );
final verdantium.standard.data.pdx_HyperButtonModel_pdx_PairRef t2 = pdx_zero( t1.getMilieu() , (verdantium.standard.data.pdx_HyperButtonModel_pdx_ObjectRef)( t1.getObject() ) );

return( t2 );
}
	public static verdantium.standard.data.pdx_HyperButtonModel_pdx_PairRef pdx_zero( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final verdantium.standard.data.pdx_HyperButtonModel_pdx_ObjectRef in )
{
final verdantium.standard.data.pdx_HyperButtonModel_pdx_PairRef tx = new verdantium.standard.data.pdx_HyperButtonModel_pdx_PairRef( in , pdx_thismilieu );
final jundo.runtime.ExtMilieuRef t0 = tx.getMilieu();
final jundo.runtime.ExtMilieuRef t1 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "image" , t0 , null );
final jundo.runtime.ExtMilieuRef t2 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "labelText" , t1 , null );
final jundo.runtime.ExtMilieuRef t3 = jundo.runtime.Runtime.asgIntObjectMember( tx.getObject() , "paramVal" , t2 , 0 );
final jundo.runtime.ExtMilieuRef t4 = jundo.runtime.Runtime.asgIntObjectMember( tx.getObject() , "imageMode" , t3 , 0 );
final jundo.runtime.ExtMilieuRef t5 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "macroList" , t4 , null );
final jundo.runtime.ExtMilieuRef t6 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "resultTable" , t5 , null );
final jundo.runtime.ExtMilieuRef t7 = jundo.runtime.Runtime.asgJobjObjectMember( tx.getObject() , "imageBytes" , t6 , null );
final verdantium.standard.data.pdx_HyperButtonModel_pdx_PairRef z = new verdantium.standard.data.pdx_HyperButtonModel_pdx_PairRef( in , t7 );
return( z );
}
	public static void pdx_initClassMembers( )
{
}

	static
{
pdx_initClassMembers();
}

	public java.lang.Object pdx_ObjectMemberAccess_pdx_getimage( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "image" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgimage( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "image" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getlabelText( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "labelText" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asglabelText( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "labelText" , mil , val ) );
}
	public int pdx_ObjectMemberAccess_pdx_getparamVal( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getIntObjectMember( this , "paramVal" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgparamVal( final jundo.runtime.ExtMilieuRef mil , final int val )
{
return( jundo.runtime.Runtime.asgIntObjectMember( this , "paramVal" , mil , val ) );
}
	public int pdx_ObjectMemberAccess_pdx_getimageMode( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getIntObjectMember( this , "imageMode" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgimageMode( final jundo.runtime.ExtMilieuRef mil , final int val )
{
return( jundo.runtime.Runtime.asgIntObjectMember( this , "imageMode" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getmacroList( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "macroList" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgmacroList( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "macroList" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getresultTable( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "resultTable" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgresultTable( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "resultTable" , mil , val ) );
}
	public java.lang.Object pdx_ObjectMemberAccess_pdx_getimageBytes( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getJobjObjectMember( this , "imageBytes" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgimageBytes( final jundo.runtime.ExtMilieuRef mil , final java.lang.Object val )
{
return( jundo.runtime.Runtime.asgJobjObjectMember( this , "imageBytes" , mil , val ) );
}
	public jundo.runtime.ExtMilieuRef pdxm_setImage( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_1620 = ( this ).pdx_ObjectMemberAccess_pdx_asgimage( pdx_thismilieu , ( in ) );
return( pdx_tmp_1620 );
}
	public int pdxm_getParamVal( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final int pdx_tmp_3300 = ( this ).pdx_ObjectMemberAccess_pdx_getparamVal( pdx_thismilieu );
return( pdx_tmp_3300 );
}
	public java.lang.Object pdxm_getResultTable( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_2820 = ( this ).pdx_ObjectMemberAccess_pdx_getresultTable( pdx_thismilieu );
return( pdx_tmp_2820 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setImageBytes( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_2100 = ( this ).pdx_ObjectMemberAccess_pdx_asgimageBytes( pdx_thismilieu , ( in ) );
return( pdx_tmp_2100 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setImageMode( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final int  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_1140 = ( this ).pdx_ObjectMemberAccess_pdx_asgimageMode( pdx_thismilieu , ( in ) );
return( pdx_tmp_1140 );
}
	public java.lang.Object pdxm_getImageBytes( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_1860 = ( this ).pdx_ObjectMemberAccess_pdx_getimageBytes( pdx_thismilieu );
return( pdx_tmp_1860 );
}
	public int pdxm_getImageMode( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final int pdx_tmp_900 = ( this ).pdx_ObjectMemberAccess_pdx_getimageMode( pdx_thismilieu );
return( pdx_tmp_900 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setParamVal( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final int  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_3540 = ( this ).pdx_ObjectMemberAccess_pdx_asgparamVal( pdx_thismilieu , ( in ) );
return( pdx_tmp_3540 );
}
	public java.lang.Object pdxm_getLabelText( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_3780 = ( this ).pdx_ObjectMemberAccess_pdx_getlabelText( pdx_thismilieu );
return( pdx_tmp_3780 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setLabelText( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_4020 = ( this ).pdx_ObjectMemberAccess_pdx_asglabelText( pdx_thismilieu , ( in ) );
return( pdx_tmp_4020 );
}
	public java.lang.Object pdxm_getMacroList( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_2340 = ( this ).pdx_ObjectMemberAccess_pdx_getmacroList( pdx_thismilieu );
return( pdx_tmp_2340 );
}
	public java.lang.Object pdxm_getImage( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final java.lang.Object pdx_tmp_1380 = ( this ).pdx_ObjectMemberAccess_pdx_getimage( pdx_thismilieu );
return( pdx_tmp_1380 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setMacroList( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_2580 = ( this ).pdx_ObjectMemberAccess_pdx_asgmacroList( pdx_thismilieu , ( in ) );
return( pdx_tmp_2580 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setResultTable( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final java.lang.Object  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_3060 = ( this ).pdx_ObjectMemberAccess_pdx_asgresultTable( pdx_thismilieu , ( in ) );
return( pdx_tmp_3060 );
}
	}

